### ISSUE TITLE
Add support for SASL authentication

### ISSUE THREAD

**Issue by coxjc** [robinhood/faust#122]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

N/A

## Expected behavior

Ideally, there would be the (documented) ability to connect to a remote Kafka broker via SASL authentication. 

## Actual behavior
I searched through the docs & spent a while `grep`ing, and I found no way to authenticate/connect to a remote Kafka broker. 

# Versions

N/A

**Comment by ask** [comment]
The broker is specified in the app configuration:

```

app = faust.App(broker='kafka://host1;host2`)

I'm actually unsure about SASL authentication, but if aiokafka supports it we should definitely also.

**Comment by vineetgoel** [comment]
I do see that `aiokakfa` supports SSL Authentication. Would this work for you? If yes, it should be fairly simple for us to add support for this.

**Comment by ask** [comment]
aiokafka supports SSL, but not yet SASL: https://github.com/aio-libs/aiokafka/issues/84

**Comment by fisuk** [comment]
@ask Now that aiokafka has support for SASL plain, would it be possible to get it working on Faust as well?

**Comment by tutu86** [comment]
Is there anyone that could able to use faust with SASL/SCRAM connection method? I use Cloud Karafka as our Kafka service provider. In production i need to connect with SASL/SCRAM =(
