### ISSUE TITLE
[Documentation] Introducing Faust

### ISSUE THREAD

**Issue by nvictor** [robinhood/faust#125]
My apologies if I am getting this wrong. Not sure what would help better. Here's another typo on the Introducing Faust page:

```
@app.agent(orders_kafka_topic)
async def process(order: faust.Stream[Order]) -> None:
```

Should read

```
@app.agent(orders_kafka_topic)
async def process(orders: faust.Stream[Order]) -> None:
```

**Comment by vineetgoel** [comment]
Hey @nvictor thanks for pointing this out. Would you like to create a PR for this and I can merge it in?

I'll make the change in a couple days if I don't hear back but I want to give you the chance to get credit for finding this typo :)
