### ISSUE TITLE
Unfortunate choice of project name

### ISSUE THREAD

**Issue by SpotlightKid** [robinhood/faust#129]
Are you aware that there is already a well established Open Source project called FAUST (Functional Audio Stream), a programming language for DSP tasks?

http://faust.grame.fr/about/

Since this also concerned with streams, albeit in a different sense, this is a potential source of considerable confusion.

**Comment by ask** [comment]
These are contextually completely different.
I doubt anyone will confuse the DSP faust as a stream processing technology, nor will anybody confuse our faust for a tool used to process audio.  It will be obvious by context which one is meant.



robinhood/spark, is also in name collision with a very popular tool but it's not been a big problem.

PS: If they have very long beards they are most likely talking about the DSP project!

**Comment by SpotlightKid** [comment]
Ok, I just thought, I'd let you know.
