### ISSUE TITLE
Add run_once with on_leader: bool param to faust.App

### ISSUE THREAD

**Issue by okuznetsov** [robinhood/faust#131]

**Comment by ask** [comment]
Do you want a task that executes on the leader at startup?

If so maybe we should add `on_leader` support to @app.task:

```py
@app.task(on_leader=True)
async def run_on_leader_after_worker_started():
    print("I am the leader.")
```

**Comment by vineetgoel** [comment]
@okuznetsov if what the goal is to run something upon start up of an app, and to run it only one of the workers, we do something like this as such:

```
@app.task()
async def run_on_leader_after_worker_starter():
    if app.is_leader():
        print("I am the leader.")
```

But yeah, we can add this to `@app.task` as a parameter too.
