### ISSUE TITLE
Raise error if num.partitions mismatch between source topic and changelog/repartition topic

### ISSUE THREAD

**Issue by ask** [robinhood/faust#137]
1) If agent is reading from topic with 8 partitions

   - but create a table with changelog having 4 partitions

   - or use groupby() to repartition but create repartitioning topic having 4 partitions.

This would be a bad thing, should we raise an error in this case?

**Comment by vineetgoel** [comment]
Yeah I think we should explicitly raise an error in this case. This can result in confusion.

**Comment by vineetgoel** [comment]
@ask this is done right?

**Comment by ask** [comment]
Not implemented AFAIK
