### ISSUE TITLE
Custom Partitioner

### ISSUE THREAD

**Issue by wuttem** [robinhood/faust#164]
What would you recommend to implement a custom partitioner?

I am currently monkey patching faust.transport.drivers.aiokafka.Producer to overwrite
```python
def key_partition(self, topic: str, key: bytes) -> TP:
    partition = random.randint(0, 4)
    return TP(topic, partition)
```

Is there a better way ? Is there already a possibility to send **kwargs parameters to the Producer init of the aiokafka ? would you want a pull request to set this parameter via config ?

**Comment by vineetgoel** [comment]
This is probably a bad idea as it might break some of the faust functionality such as leader election and tables.

If the key is not super important for you, I would recommend not assigning the key in order to get random partitioning. 

Or create a key model as such:

```
class KeyWithRandom(faust.Record):
    key: K
    seed: float = None

    def __post_init__(self) -> None:
        if self.seed is None:
            self.seed = random.random()
```

and use the following key for your messages: KeyWithRandom(key=key). This will preserve your keys and yet allow your messages to be randomly distributed rather than by the key.

**Comment by wuttem** [comment]
Thanks for the reply! 
Unfortunatly the random function was just an example ... in practice i want to partition on a part of a composite key which is avro serialized.
Do you think it might work to subclass the transport and init the producer of the aio library with the custom partitioner or is there any code in faust that will partition with another method than the one from the used transport ...

**Comment by vineetgoel** [comment]
I think you could do that or you could add a partitioner function to a topic, agent (basically anything that has an underlying channel). However is there a reason you can just create a new key based on what you want to partition by?

For example if I have an incoming model:

```
class MyModel(faust.Record):
    a: int
    b: str
    c: str
```

And I am reading messages where the key is of type `MyModel` and want to create a new topic which is partitioned by `b` or `b` and `c`, then could you create the key accordingly for the new topic that you are writing to?

**Comment by wuttem** [comment]
For future reference:

I got it to work (for us) with patching Producer creation method of the aiokafka driver in faust.
Code looks like this:

```python
from faust.transport.drivers.aiokafka import server_list, cast, Transport, Producer
from aiokafka.producer.producer import DefaultPartitioner

def my_partitioner(key, all_partitions, available_partitions):
    if ...:
        return all_partitions[...]
    # Fallback Partitioner
    return DefaultPartitioner()(key, all_partitions, available_partitions)

@monkeypatch_method(Producer)
def on_init(self) -> None:
    transport = cast(Transport, self.transport)
    conf = transport.app.conf
    self._producer = aiokafka.AIOKafkaProducer(
        loop=self.loop,
        bootstrap_servers=server_list(
            transport.url, transport.default_port),
        client_id=conf.broker_client_id,
        acks=self.acks,
        linger_ms=self.linger_ms,
        max_batch_size=self.max_batch_size,
        # --- CHANGE Partitioner
        partitioner=my_partitioner,
        # --- CHANGE Partitioner
        max_request_size=self.max_request_size,
        compression_type=self.compression_type,
        on_irrecoverable_error=self._on_irrecoverable_error,
        security_protocol="SSL" if conf.ssl_context else "PLAINTEXT",
        ssl_context=conf.ssl_context
    )
```

If you add a setting to assign a custom partitioner we would definitely use it.

Thank you for open sourcing the Lib and providing answers and support. Really appreciate it.

**Comment by ask** [comment]
New setting `producer_partitioner` will be in Faust 1.2
(d1e08a0f3b4a76b079dd110041ca89f34cc61b74)
