### ISSUE TITLE
Run faust without web server

### ISSUE THREAD

**Issue by denizkaanaraci** [robinhood/faust#167]
I want to run multiple faust workers with docker. But I couldn't find how to start worker without web server.

**Comment by g-rd** [comment]
I am also new to faust, but as far as I understand is that you should start
every worker on different port.

g-rd

**Comment by denizkaanaraci** [comment]
I know I should do it like that but I don't want to use it with web server.

**Comment by g-rd** [comment]
I am trying to figure out something similar actually, I am currently unsure
and confused with the architecture of faust, I don't want to believe that
it really is necessary to run every worker on separate ports because in my
case I would need to run around a few hundred workers and wound't want them
all to listen on separate ports either.

If I figure it out I'll let you know, or if you have some ideas, perhaps
you can let me know, I am interested in a similar thing.

Best,

Gerd

**Comment by ask** [comment]
Disabling the web server should be fine, stream processing works perfectly well without it. We should add an option `--without-web` for example.

We could split these into two additional libraries:

- models
   Models and Records are used by web, faust, and is generally useful.
- web
   Simple abstraction on top of aiohttp that will help us experiment with other frameworks (Sanic?)
   With support for using models as API serializers


Having everything in `faust` means there's some bloat for people who don't use that functionality,
but the alternative is for users to learn four different libraries: mode, faust, models, web,
this will quickly get confusing.  Fabric 2.x recently switched to such an organization where they have fabric and invoke. Remembering what is defined where is quite painful to me, and I guess also other users.

**Comment by denizkaanaraci** [comment]
Thanks for answering. When will you plan to do it?

**Comment by bolorundurovj** [comment]
> Disabling the web server should be fine, stream processing works perfectly well without it. We should add an option `--without-web` for example.
> 
> We could split these into two additional libraries:
> 
> * models
>   Models and Records are used by web, faust, and is generally useful.
> * web
>   Simple abstraction on top of aiohttp that will help us experiment with other frameworks (Sanic?)
>   With support for using models as API serializers
> 
> Having everything in `faust` means there's some bloat for people who don't use that functionality,
> but the alternative is for users to learn four different libraries: mode, faust, models, web,
> this will quickly get confusing. Fabric 2.x recently switched to such an organization where they have fabric and invoke. Remembering what is defined where is quite painful to me, and I guess also other users.

Any update on this?
