### ISSUE TITLE
Full example that shows how to do autodiscover in a stand alone app

### ISSUE THREAD

**Issue by robertrbruno** [robinhood/faust#170]
With current documentation we are having issues getting autodiscover to work.  An example that shows a main program with the app and then some submodules with say some tasks, agents, etc would be very useful.

**Comment by robertrbruno** [comment]
Also if possible can you show in the example how the main app can then launch multiple workers.

**Comment by vineetgoel** [comment]
Closing this issue. Please feel free to reopen if there are any other questions :)
