### ISSUE TITLE
source and sink example

### ISSUE THREAD

**Issue by Madhu1512** [robinhood/faust#179]
Is there an example on how to setup faust to consume the data from kafka and write to single or multiple sinks ( elasticsearch, cassandra etc..)

sample code  ( I am not sure the sample code setup is proper way to read and write into the sink)

    import faust

    app = faust.App(
       'demo',
        broker='kafka://localhost:9092',
        value_serializer='raw'
    )

    message_topic = app.topic('demo')

    @app.agent(message_topic)
    async def mystream(stream):
       async for message in stream:
          await sink.send(value=message.decode('utf-8'))

    @app.agent()
    async def sink(messages):
       async for msg in messages:
          print(msg)

**Comment by vineetgoel** [comment]
I think this definitely works. I have a [blog](https://robinhood.engineering/adding-faust-to-your-existing-architecture-39b0ebd1f7c9) here to show how we use it with different services (including elasticsearch)

The basic idea is you can read the messages in an agent and write to any service as long as there is a supported python asyncio client for it. 

Further, typically when writing to something like ES or Casssandra, you might want to batch your writes. In that case you can use [Stream.take](https://faust.readthedocs.io/en/latest/userguide/streams.html#take-buffer-up-values-in-the-stream).

**Comment by vineetgoel** [comment]
However note: this only answers how to write to a sink from kafka. If you want to read from some external source into Kafka, that can also be done with something like `@app.timer` but distribution, keeping track of what you have already read, etc. over there would be a bit more involved.

**Comment by codewithsk** [comment]
On a related note, I was wondering how to specify a key when using a sink. I'm reading from a Kafka topic whose key type is str. I process the message and use a different kafka topic as a sink. Now how do I specify the key for the outgoing message?

**Comment by StephenSorriaux** [comment]
Hi,

The `Topic()` object has a `send()` method that accepts a `key` parameter: https://faust.readthedocs.io/en/latest/reference/faust.topics.html#faust.topics.Topic.send
