### ISSUE TITLE
bugs about commit offset

### ISSUE THREAD

**Issue by hys20151008** [robinhood/faust#192]
I encounter a big problem about commit offset!!
when i start a faust worker,i found that there is a daemon process run in order to  auto commit offset periodically, even if ```enable_auto_commit=False``` was set.And i found that in source code

faust/transport/drivers/aiokafka.py
```
 def _create_worker_consumer(
            self,
            app: AppT,
            transport: 'Transport') -> aiokafka.AIOKafkaConsumer:
        conf = app.conf
        self._assignor = self.app.assignor
        return aiokafka.AIOKafkaConsumer(
            loop=self.loop,
            client_id=conf.broker_client_id,
            group_id=conf.id,
            bootstrap_servers=server_list(
                transport.url, transport.default_port),
            partition_assignment_strategy=[self._assignor],
            enable_auto_commit=False,
            auto_offset_reset='earliest',
            max_poll_records=None,
            max_partition_fetch_bytes=1048576 * 4,
            fetch_max_wait_ms=1500,
            check_crcs=conf.broker_check_crcs,
            session_timeout_ms=int(conf.broker_session_timeout * 1000.0),
            heartbeat_interval_ms=int(conf.broker_heartbeat_interval * 1000.0),
            security_protocol="SSL" if conf.ssl_context else "PLAINTEXT",
            ssl_context=conf.ssl_context,
        )
```
though ```enable_auto_commit=False``` set in func ```_create_worker_consumer```, but there always a daemon task start when faust worker start. just see below source code:

faust/transport/consumer.py
```
    @Service.task
    async def _commit_handler(self) -> None:
        await self.sleep(self.commit_interval)
        while not self.should_stop:
            await self.commit()
            await self.sleep(self.commit_interval)
```

**I think this task must stop** when ```enable_auto_commit=False```!!!,so i can commit offset manually,but it is not!!
Another question is that when process message encounter a Exception, faust will commit offset(it should not commit offset in my opinion)

faust/transport/consumer.py
```
async def on_task_error(self, exc: BaseException) -> None:
        await self.commit()
```

 it's a bug  i think

# Versions

* Python version  3.6.5
* Faust version     1.2.1
* Operating system centos 7.8
* Kafka version     2.0

@vineetgoel @ask

**Comment by mohamedashrafamin** [comment]
Same here, i hope issue will be resolved ASAB.

**Comment by paularmand** [comment]
Concerning the commit on error, I believe this is by design and also as such in the documentation. Faust will however not be able to commit if the worker was killed instantly. See documentation at http://fauststream.com/en/stable/userguide/settings.html#stream-ack-exceptions
