### ISSUE TITLE
[question] - agent, worker and concurrency

### ISSUE THREAD

**Issue by DeoLeung** [robinhood/faust#209]
Hi I'm new to this library and after exploring with some examples , I have some questions about it

1. is there a way to dynamic set `concurrency` of agent, so I don't need to modify the code and restart worker to scale in a single worker
2. are all agents (multiple functions) run on a single event loop in a worker?
3. sometimes I will need some agents to do blocking functions(like calculation), is there a way to have a thread pool worker? (not very familiar with `gevent`, `eventlet`, will have a look later though)
4. sharing property, like I will have a single http client for all agent(tornado pycurl), is writing the client outside the correct way?
```python
CONCURRENCY = 20

http_client = CurlAsyncHTTPClient(max_clients=CONCURRENCY)


@app.agent(topic, concurrency=CONCURRENCY)
async def send_message(messages: StreamT[Message]):
  async for message in messages:
    # use the http client
    ...
```

thanks

**Comment by ask** [comment]
1. No, you cannot set concurrency dynamically for an agent.

I don't think this is all that problematic: idle coroutines are idle and take up a bit of memory - that's it.

What you may want is a shared task pool to execute your tasks when you have multiple agents.
Let's say you have one agent A with concurrency 500, and another agent B with concurrency 500.
If there is lots of work for agent A to do, but little for agent B, most of the concurrency slots for agent B will be idle.

I think we need some way of sharing concurrency between agents for this to be optimal.

2. Yes, all agents run on the same thread and share the same event loop for now.

3. You can have the agent process the event in a separate thread by using `loop.run_in_executor`

4. We actually have a aiohttp client session available on the app already:

```py
@app.agent()
async def process(stream):
    async for message in messages:
         async with app.http_client.get(message.url) as response:
              json_payload = await response.json()
```

We don't have any concurrency control in this case, but you could define your own `aiohttp.ClientSession` and configure it however you want.

**Comment by DeoLeung** [comment]
thx for the clarification, currently we have some external service access using tornado http client, may need a while to switch to aiohttp, anyway that's not a big problem

**Comment by AHLinJie** [comment]
cloud be change agent.concurrency then agent.restart
