### ISSUE TITLE
Pass `request_timeout_ms` to `AIOKafkaConsumer`

### ISSUE THREAD

**Issue by martinmaillard** [robinhood/faust#219]
Hi,

I didn't find any way to change the default value of `request_timeout_ms` of `AIOKafkaConsumer`. I will probably give it a try and submit a PR. Does anyone have any advice as to where this param should be defined by the user? I'm guessing a `transport_request_timeout` setting passed to `faust.App`.

Thanks

**Comment by ask** [comment]
This would be great! You would have to define it here:

faust.types.settings - this defines the settings passed to `App(...)`
https://github.com/robinhood/faust/blob/master/faust/types/settings.py

document it here:
https://github.com/robinhood/faust/blob/master/docs/userguide/settings.rst

then pass it to the aiokafka transport consumer.

**Comment by martinmaillard** [comment]
PR is merged. The setting is called `broker_request_timeout`. I will close this issue.
