### ISSUE TITLE
New version of coloredlogs has breaking

### ISSUE THREAD

**Issue by amerski99** [robinhood/faust#241]
The new version of coloredlogs has breaking changes that causes faust not to startup.  (maybe this is more of an issue with a mode, but it seems like it could/should be able to be configured via faust to set a stream)

https://github.com/borntyping/python-colorlog/commit/40280b4bb36d8ad1a8bf1cfaa159a4a9066b1126#diff-58e8d864ceb9f791b89e0b6364b5e233

**Comment by Fahreeve** [comment]
same as  #240

**Comment by ask** [comment]
Thanks! This is now fixed in faust 1.4.2
