### ISSUE TITLE
Search results still broken :(

### ISSUE THREAD

**Issue by chrisseto** [robinhood/faust#243]
Search results on faust.readthedocs.io still point to http://fauststream.com.

https://github.com/robinhood/faust/issues/157
https://github.com/robinhood/faust/issues/126

**Comment by ask** [comment]
Very strange, it works for me here. what are you searching for?

I've removed all references from the repository, and just now also anything with fauststream.com in it from the Readthedocs configuration.

**Comment by rwhitten577** [comment]
This has been broken for me but now it all looks good and points back to readthedocs.

**Comment by chrisseto** [comment]
Looks good for me too, I'm guessing something from readthedocs finally uncached.
Sorry for reopening!
