### ISSUE TITLE
High CPU and worker are rebalancing constantly

### ISSUE THREAD

**Issue by ST2Labs** [robinhood/faust#245]
## Checklist

![image](https://user-images.githubusercontent.com/9781565/50303788-779a9f80-048e-11e9-8af5-571c12b58fa0.png)

Running faust in docker swarm cluster, 2 Worker HIgh CPU and rebalancing every 2 minutes 

## Full traceback

```pytb
4,532: ERROR]: Error sending JoinGroupRequest_v0 to node 1002 [[Error 7] RequestTimedOutError] -- marking coordinator dead
kafka_aggregator.2.gdiosf46w0cn@me01    | [2018-12-20 18:36:14,533: WARNING]: Marking the coordinator dead (node 1002)for group wai_aggregator.
kafka_aggregator.2.gdiosf46w0cn@me01    | [2018-12-20 18:36:14,565: INFO]: Discovered coordinator 1002 for group wai_aggregator
kafka_aggregator.2.gdiosf46w0cn@me01    | [2018-12-20 18:36:14,565: INFO]: (Re-)joining group wai_aggregator
kafka_aggregator.1.i2jkhn3y5304@me01    | [2018-12-20 18:36:15,096: ERROR]: Error sending JoinGroupRequest_v0 to node 1002 [[Error 7] RequestTimedOutError] -- marking coordinator dead
kafka_aggregator.1.i2jkhn3y5304@me01    | [2018-12-20 18:36:15,097: WARNING]: Marking the coordinator dead (node 1002)for group wai_aggregator.
kafka_aggregator.1.i2jkhn3y5304@me01    | [2018-12-20 18:36:15,102: INFO]: Discovered coordinator 1002 for group wai_aggregator

```

# Versions

* Python version: 3.7
* Faust version: 1.4.1
* Operating system: Docker Container
* Kafka version: 1.1.1
* RocksDB version (if applicable)

Host (Docker Worker) | 10GB RAM / 8 CPU
Container / Service:
CPU:
 Limits: 8 CPU / 1GB RAM
 Reserved: 2 CPU / 1GB RAM

Kafka Producer Messs/Seconds : 6700 msg / seconds

¿IT's Normal ??
 What version Kafka is sopported ??

**Comment by ST2Labs** [comment]
Hi, 

I'm monitoring VM/Docker and Faust get only working on 1 CPU, even I assigned 8 CPU ¿How?

Thanks

**Comment by ask** [comment]
This is the only error?

You only have two workers, there must be some error that causes these rebalances to happen.
What about in the Kafka server logs?

> I'm monitoring VM/Docker and Faust get only working on 1 CPU, even I assigned 8 CPU ¿How?
Python has the GIL
You need to start 8 worker instances to utilize eight CPU cores.

**Comment by ST2Labs** [comment]
This seems to be only ERROR:

`kafka_aggregator.1.nw5ppz81q19w@dev01    | [2018-12-22 10:08:01,724: INFO]: Fetch offset 234864807 is out of range for partition TopicPartition(topic='TOPICz', partition=4), resetting offset`

Thanks in advanced !!
And Merry XMAS !

**Comment by ST2Labs** [comment]
Hi, 

- CPU keep on high, even if I start 8 faust worker always have 100% CPU.

I have one list and every 120s process data, but with 7000 message/seconds used high CPU and RAM, 6 cores 100% and 15GB/RAM, even through exceptions Memory Error.

Kafka: 2.1.2 / Cluster with 3 Nodes
Partitions: 12
Ubuntu 18.04
Python 3.6.7
RAM: 15GB
CPU: 6 cores

¿any idea?

Thanks in advance

**Comment by ST2Labs** [comment]
Hi, 

With Kafka 2.12 and running faust python 3.6.7 on ubuntu 18.04, it's running all worker (8) good, no more High CPU and rebalancing.

Thanks for all! 
Great works, thank for sharing !!!

**Comment by ask** [comment]
This issue should be fixed :tada:
