### ISSUE TITLE
How to get Kafka Headers value for a particular topic

### ISSUE THREAD

**Issue by learnermaxRL** [robinhood/faust#273]
## Checklist

- [ ] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce
I can access the values which were dumped in Kafka,can you please tell us how to get value of kafka headers?

## Expected behavior

Tell us what you expected to happen.

## Actual behavior

Tell us what happened instead.

## Full traceback

```pytb
Paste the full traceback (if there is any)
```

# Versions

* Python version : 3.6
* Faust version 1.4.2
* Operating system Ubuntu 16.04
* Kafka version 2.11-2.1.0
* RocksDB version (if applicable)

**Comment by ask** [comment]
Kafka headers functionality was recently added to kafka-server 0.11, and we yet to add
support for them in Faust.

**Comment by ask** [comment]
It's also not yet available in the Kafka client that we use: https://github.com/aio-libs/aiokafka/issues/462

**Comment by learnermaxRL** [comment]
Can we get timestamp ?

**Comment by ask** [comment]
Both headers and timestamp is now implemented in master
