### ISSUE TITLE
connecting error

### ISSUE THREAD

**Issue by MohMehrnia** [robinhood/faust#274]
When I try to connect kafka with below code, show me connection error message:
```
import faust

app = faust.App('exmaple', broker='kafka://localhost:9092')

@app.agent()
async def myagent(stream):
    async for event in stream:
        print(event)
```

Error Message:
rhkafka.errors.ConnectionError: ConnectionError: No connection to node with id 1001

**Comment by ask** [comment]
Do you have Kafka running locally?

**Comment by MohMehrnia** [comment]
Yes i run locally, but thanks my problem solved, i used docker for zookeeper and kafka and zookeeper name is not in dns host file in windows
