### ISSUE TITLE
Goethe citation source incorrect

### ISSUE THREAD

**Issue by henschkowski** [robinhood/faust#283]
## Checklist

- [X] I have included information about relevant versions --> master branch
- [X] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Maybe this is pedantic. But it is easy to fix:

Open Userguide, "streams" chapter (docs/userguide/streams.rst) 
On top of the page, there is a citation “Everything transitory is but an image.” with source "Goethe, Faust: First part". 

It should read "Goethe, Faust: Part II", or simply "Goethe, Faust".

**Comment by ask** [comment]
Thanks! I changed it in master. This is the type of detail we want to be perfect :)

**Comment by ask** [comment]
Interestingly there's a lot of references on Google that says this is from the first part, but digging into it it's the final words of part two.
Alles Vergängliche / Ist nur ein Gleichnis
