### ISSUE TITLE
group_by in multiple agents results in duplicate messages.

### ISSUE THREAD

**Issue by Atreus-Technologies** [robinhood/faust#284]
Just a brief question/possible unexpected behaviour I identified when creating agents. It appears that the group_by function creates a new Kafka topic and publishes all messages received to that topic. This then causes issues if a second agent requiring the same distribution among nodes is created (e.g. for a second table with different windowing or calculation).

## Steps to reproduce

My interpretation could be completely wrong here, but I believe if you have two agents listening to the same stream and want both of them to group by the same key, having not defined a name parameter for either, they will both listen to the same (repartitioned) topic, which can cause unexpected outcomes. e.g.
running the below gives you the message twice, once from each agent;
 
```
import faust, asyncio
loop = asyncio.get_event_loop()
app = faust.App('test_app', broker='kafka://kafka:9092', loop = loop)
topic_a = app.topic('test_topic')

class test_record(faust.Record):
    field1:str
    field2:str
@app.agent(channel = topic_a)
async def agent_a(topic):
    async for msg in topic.group_by(test_record.field1):
        print(f'from agent_a: {msg}')
@app.agent(channel = topic_a)
async def agent_b(topic):
    async for msg in topic.group_by(test_record.field1):
        print(f'from agent_b: {msg}') 
w = faust.Worker(app = app,
             debug=True,
             loop=loop,
             loglevel='INFO')
asyncio.ensure_future(w.start(), loop=loop)
asyncio.ensure_future(w.app.start(), loop=loop)
await topic_a.send(value=test_record.loads(
    {'field1':'testfield1','field2':'testfield2'}))
```
*(Apologies for the peculiar startup method, I'm in Jupyter and need to hook  into its event loop, better suggestions appreciated.)*

But running the below code gives you the same message four times. Actually, I'm a bit uncertain (based on my assumptions above) as to why it doesn't get stuck in an infinite loop? Maybe this behaviour is completely expected and I've just misread the docs, in which case apologies.

```
import faust, asyncio
loop = asyncio.get_event_loop()
app = faust.App('test_app', broker='kafka://kafka:9092', loop = loop)
topic_a = app.topic('test_topic')

class test_record(faust.Record):
    field1:str
    field2:str
@app.agent(channel = topic_a)
async def agent_a(topic):
    async for msg in topic.group_by(test_record.field1):
        print(f'from agent_a: {msg}')
@app.agent(channel = topic_a)
async def agent_b(topic):
    async for msg in topic.group_by(test_record.field1):
        print(f'from agent_b: {msg}') 
w = faust.Worker(app = app,
             debug=True,
             loop=loop,
             loglevel='INFO')
asyncio.ensure_future(w.start(), loop=loop)
asyncio.ensure_future(w.app.start(), loop=loop)
await topic_a.send(value=test_record.loads(
    {'field1':'testfield1','field2':'testfield2'}))
```

## Expected behavior

Based on the paradigm that agents listen to the topic given in the @app.agent decorator, I hadn't expected logic within the agent (being the 'group_by' statement) would affect the stream the agent was listening to, much less the logic of a wholly separate agent. This was a little tricky to debug, so maybe I've misread the problem; if I'm correct I think the behaviour could be documented a little more thoroughly. 

I can't see a mention of it in the docs currently, and (while I imagine that for most simple applications, you'd want to do all your processing for a given repartition within a single agent for efficiency) I'd suggest a run time warning when the second agent comes online stating that this will occur. Even better would be a breaking change to optimise the group_by function and ensure that only a single agent ever repartitions the topic. However this would neccesitate logic to track which agents are grouping which topics and handle failover where the designated grouping agent terminates, as well as additional logic to allow for placement of grouping agents within the cluster. Probably too complicated, but maybe also a good value-add for this library and probably within its intended scope.

# Versions

* Python 3.7.1
* Faust 1.4.5
* Debian
* N/A
* N/A

**Comment by ask** [comment]
Ah, this makes sense actually.  The group_by method will create a new topic with an autogenerated name, the problem is that both agents end up using the same name for their intermediate topic.

`test_topic-foo-test_record.field1-repartition`

We should include the agent name in this topic

**Comment by Atreus-Technologies** [comment]
@ask, thanks for confirming, I'm pleased I wasn't too far off. Your solution would certainly work; is there any interest in implementing a design similar to my suggestion in issue #300? For efficiency (and to avoid cluttering Kafka) would it make sense to;
1. Have a single Faust topic for each physical Kafka topic.
2. Map the concept of an agent to a consumer group (not a topic, as is current state, from my understanding).
3. Treat workers as instantiations of agents s.t. each worker is a consumer instance within its consumer group (or possibly multiple consumer instances, between mutually exclusive groups)
4. Perform some sort of automatic optimisation across group-bys to ensure that only a single topic is ever created for a given group by operation within a given topic.

Would this help avoid the proliferation of topics as functionality is split into the individual agents? I'm purely thinking about keeping the Kafka data structures as simplistic as possible, and it also seems that (especially to motivate the use of workers) a given agent should possibly act as a consumer group rather than instantiating a whole new topic. 

Perhaps the more interesting question - if the functionality I'm describing around group-bys were to be considered optional, then where would it best sit in Faust's architecture? Wherever it went, it would need to be relatively isolated so it could be turned on and off, and I can't see a clean abstraction for the way that group bys are created at the moment, which might become an architectural weakness down the track. Near term, I'm reluctant to create forks of your repo to execute this - there is strength in numbers I always think.
