### ISSUE TITLE
How to configure readinessProbe for faust consumers 

### ISSUE THREAD

**Issue by zamai** [robinhood/faust#286]
Hi, 

I'm running Kafka in production on a kubernetes cluster and I'm wondering how can I check the readiness of the Faust worker from the perspective of the cluster(readinessProbe)?  

When deploying new versions of the app it is important for my application to only send traffic to the new version of the app when it successfully connects to the Kafka cluster, joins consumer groups etc. Only then I'd consider this worker ready to accept traffic and kubernetes can terminate the older version of the worker.

[Readiness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-readiness-probes) can be configured with the bash command that is executed in the pod, or HTTP request send to web server. 

I'd be happy to contribute back and add readinessProbe to the `examples/kubernetes/consumer.yaml`.

**Comment by danpilch** [comment]
I think faust workers expose a simple api:

`curl 127.0.0.1:6066 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   498  100   498    0     0   506k      0 --:--:-- --:--:-- --:--:--  486k
{
  "Sensor0": {
    "messages_active": 0,
    "messages_received_total": 0,
    "messages_sent": 0,
    "messages_sent_by_topic": {},
    "messages_s": 0,
    "messages_received_by_topic": {},
    "events_active": 0,
    "events_total": 0,
    "events_s": 0,
    "events_runtime_avg": 0,
    "events_by_task": {},
    "events_by_stream": {},
    "commit_latency": [
      3.509293310344219e-05
    ],
    "send_latency": [],
    "topic_buffer_full": {},
    "tables": {},
    "metric_counts": {},
    "topic_committed_offsets": {},
    "topic_read_offsets": {},
    "topic_end_offsets": {}
  }
}
`

**Comment by Djoels** [comment]
Being very new to this, with also a Kubernetes setup where Faust consumes and forwards to Elasticsearch.
I'm wondering whether the localhost:6066 endpoint is more feasible for the liveness probe. Shouldn't a readiness probe instead reflect external dependencies not being in order? Suppose Kafka goes down... Isn't it better to have an init container and readiness probe that reflects this state (and curl to that service, for instance).
Please tell me if I'm missing something. I also noticed that if kafka is down, there is quite a lot of logging. Is that somehow something that can be reduced or exposed through the metrics above instead?

**Comment by ask** [comment]
@Djoels So availability may not depend on Kafka being up!

Core faust consists of several components:

- Kafka (stream processing)
- RocksDB (table cache)
- Web server

If Kafka goes down we may still serve HTTP traffic and provide read-only access to table data.

Some applications may have strict availability requirements for tables, while for others
it will be OK to serve possibly stale data.

Further there are different states in the worker that can decide "readiness":

- Is the worker rebalancing? (stream processing offline, but tables cannot change at this point)
- After rebalancing the worker will start recovering tables from changelog topics,
   some applications may want to wait until this is done to decide that the system is ready.
- After recovering tables we start recovering *standby* partitions (read-only replicas used for failover)

I think this needs some documentation....

>I also noticed that if kafka is down, there is quite a lot of logging. Is that somehow something that can >be reduced or exposed through the metrics above instead?

Indeed! I wonder if we should make most of these INFO severity?
The logging here happens in aiokafka. Usually that would be out of our control,
but currently we have forked that project to make some fixes. Eventually we want to merge
those changes upstream, so need to keep that in mind.

**Comment by nilansaha** [comment]
@zamai Did you figure it out ? I am considering faust for something at work but not sure exactly how to implement the readiness and liveliness probes. Any help would be appreciated.
