### ISSUE TITLE
Combining streams with & only iterates over the first stream

### ISSUE THREAD

**Issue by mihatroha** [robinhood/faust#288]
## Steps to reproduce
```
import  faust

app = faust.App('stream_combiner',
                broker='kafka://localhost:9092',
                value_serializer='raw')

in_topic_1 = app.topic('in_1')
in_topic_2 = app.topic('in_2')

@app.agent(in_topic_1)
async def topic_merger(in_stream_1):
    async for value in (in_stream_1 & in_topic_2.stream()):
        print(value)
        yield value
```
## Expected behavior

According to the documentation on combining streams  ([https://faust.readthedocs.io/en/latest/userguide/streams.html#combining-streams](url)), the code snippet should print all the values in `in_stream_1` and in `in_topic_2.stream()`.

## Actual behavior

Only values from `in_stream_1` are printed.

# Versions

* Python version: 3.6
* Faust version: 1.4.6
* Operating system: macOS
* Kafka version: 2.1.0
* RocksDB version (if applicable): N/A
#

**Comment by ask** [comment]
This was added for use in joins, but is currently not working.

You can consume from multiple topics by specifying multiple topics in the topic description:

`@app.agent(app.topic('foo', 'bar'))`

We want to support joins, but are currently rethinking the API to use for it.

**Comment by akbhat** [comment]
With Faust 1.7.3, neither the reported syntax nor the "workaround" suggested syntax of @app.agent(app.topic('foo', 'bar')) works. Is there a different syntax that is expected to work with the latest version?

**Comment by yinrong** [comment]
join streams not working? just about to try Faust

**Comment by dqii** [comment]
I wanted to check on this as well^

**Comment by benhowes** [comment]
> With Faust 1.7.3, neither the reported syntax nor the "workaround" suggested syntax of @app.agent(app.topic('foo', 'bar')) works. Is there a different syntax that is expected to work with the latest version?

Just a note to say that I am not seeing problems with subscribing to multiple topics, both topics are consumed fine

**Comment by lightoyou** [comment]
this is working now ?
