### ISSUE TITLE
Consumption flow control

### ISSUE THREAD

**Issue by mihatroha** [robinhood/faust#291]
I would like to have more control which topic-partitions Faust fetches the messages from in each iteration. By default Consumer will fetch from all partitions, effectively giving these partitions the same priority. However in some cases, one would want for some partitions to have higher priority (say they have more lag and you want to catch up). AIOKafka Consumer already supports this behaviour (see https://aiokafka.readthedocs.io/en/stable/consumer.html#consumption-flow-control) and I think that it would be useful to expose it in Faust as well.

1. Is there a way to implement consumption flow control without changing the existing Faust library? 
2. If not, would you accept a PR that addresses this issue? I guess one would have to push the function that is responsible for the flow control to getmany method of Consumer in aiokafka.py.

**Comment by ask** [comment]
I don't think you can easily do this without changing the library.
You do have access to the consumer state (in app.consumer), but the API is more on the internal side.

I think the best way to go about this would be to expose a "scheduling strategy".
The default strategy that we have now is to do 1) round-robin between topics, 2) round robin between the partitions in those topics.  A custom scheduling strategy could prioritize topics with more lag.

**Comment by mihatroha** [comment]
A custom "scheduling strategy" would do the job.

To implement this, I would do the following:
1. Create an abstract class for scheduling strategy.
2. Put the code that implements the default scheduling strategy together in a separate class that inherits from the base class above. At the moment, 1) the outer loop that does round-robin between topics is part of getmany method in the Customer class and 2) the inner loop that does round-round between partitions is implemented in TopicBuffer class in utils. That would now all be in one place.
3. Allow for a custom scheduling strategy that is passed externally to the app.topic()

Is that okay?

**Comment by ask** [comment]
This is merged into master! Thanks, will definitely be a useful addition
