### ISSUE TITLE
Defining agents programmatically

### ISSUE THREAD

**Issue by chobeat** [robinhood/faust#300]
Hello people.

I'm working with faust 1.4.5 and I'm trying to define agents programmatically. I almost did it but there's an inconsistent behavior.

Here's how I do it

```
for transformation in get_transformations():

    async def _func(messages):
        service=Service(transformation,config)
        async for message in messages:
           # do stuff
            yield result

    _func.__name__=transformation.name
    locals()[transformation.name]=_func
    app.agent(app.topic(transformation.input_topic,
                        value_serializer="raw"))((transformation.input_topic,locals()[transformation.name],))
```
(ignore the part with the locals, it's not really necessary)

The code work flawlessly as long as I have only one agent. When I have more than one, a message on the topic associated to an agent is delivered to another agent. If I list the agents with the associated command, the topic-agent association looks correct. Obviously on my side the input<->function association is correct (I'm migrating existing services to Faust). 

My  assumption is that by defining the agents in this way, some reflection mechanism breaks but I cannot understand what. To further validate this assumption, one important piece of information is that the order in which I define the agents  change the behavior. So probably something gets overwritten at every step in the loop and the last agent gets associated to all the topics or viceversa.

Is there a way to debug this? Some internal variable to check? Because with the debug messages and `agents` command, everything seems correct.

**Comment by Atreus-Technologies** [comment]
Have a look at issue #284 and see if it might be related. My suspicion (based on a really brief skim of your problem) is yes, but I haven't had any feedback as yet, so could be completely off base. 

If it is related, try defining a name for the topics referred to by your agents. It isn't efficient - as agents multiply you'll end up with a proliferation of topics, especially once group_bys and through operations come into play. But it will get your app working in the short term, without this crazy cross-agent messaging passing happening. In my personal view, agents should map to consumer groups, not directly into topics, and workers into instances of a consumer within those consumer groups.

However I'm not in a position to fully comprehend the requirements leading to the design decisions, much less the design decisions themselves. It's something I'd like to see better doco on, if the maintainers see this. A spec or statement of intention is a good way to start a project, in my experience.

**Comment by chobeat** [comment]
An agent indeed maps to a consumer group in my case: 1 agent, 1 input-topic, 1 output-topic,1 consumer group, 1 function, 1 message type. I break down the features this way to have a simple abstraction and being indipendent from the execution mode (in this case I'm replacing my simple kafka-consumer/kafka-producer approach with faust). Right now the topology is defined by the connecting topics but tomorrow it should be implemented as a topology of agents. 

Anyway I appreciate your concern for my design. I'm bringing a system of event-driven services to Faust and I'm not 100% sure it's a solid design choice, but I'm still in an experimentation phase so any criticism at this stage is more than welcome.

I will check the issue you linked and see if it helps.

**Comment by Atreus-Technologies** [comment]
Sorry, you may have misunderstood me. A lot of these relations are defined by the way that agents instantiate topics automatically, (see the issue I linked, @ask has kindly confirmed some of my suspicions). 

It is not your design that I was commenting on, but the general design of Faust (or at least its default settings!)

**Comment by chobeat** [comment]
Ok, I see. I've also checked the issue you reported. I understand how the problem plays out. I think tomorrow I will spend quite some time trying to understand what goes wrong. Any suggestion to see how the name of the topics are instatiated? I think it's somewhere between topic and channel but maybe you delved into this issue already.

**Comment by Atreus-Technologies** [comment]
You can use whatever tool you're using to inspect Kafka topics to see the instantiation of the topics themselves (dial into your server and use some combination of kafka-topics and kafka-console-consumer). Landoop is a popular option to monitor Kafka in a more GUI oriented way, it appears - I'm a bit wary of it myself for some reason.

If you use the `name='sometopicname'` parameter on instantiation of the agent, you should be able to just experiment and see the results. That's how I figured it out :) Most entities within Faust conveniently take a `name` parameter, and tweaking this can help elucidate quite a few of the issues.

**Comment by chobeat** [comment]
The problem is that the naming is consistent. If I run `agents`, this is the output:

``` 
    name                        │ topic                      │ help  │
│ @file_deletion_requested    │ file_deletion_requested    │ <N/A> │
│ @file_uploaded              │ file_uploaded              │ <N/A> │
│ @project_deletion_requested │ project_deletion_requested │ <N/A> ```

In this specific case I'm naming the agents with the name of the topic for clarity. With this configuration, if I send a message to `file_uploaded`, `project_deletion_requested` is executed.

Naming them differently doesn't seem to give me more insight on the problem, or I don't understand what you're telling me. It's like somewhere, the last topic trumps all the others behind the scene.

**Comment by Atreus-Technologies** [comment]
Faust's inbuilt introspection capabilities are pretty limited, checking that the agents have the same name as the topics really doesn't help us much. As I said, you should use infrastructure logging tools listed above to inspect the infrastructure, if that's where you think the problem is (or to inspect the interaction between the framework and the infrastructure, which is where we'll probably find it). The core value of architectures like this is transparent introspection into the infrastructure, take advantage of this.

Now, in respect of the matter of names, if you check my comment you'll note that I've advised you to specify a name parameter. If you read the docs, a name defined in the Python code need bear no relation to the name of the agent. If you post a clean code example (e.g. without use of locals which you've explained is irrelevant) I will try to assist, as I suspect you're running up against the same issue I did in pursuing programmatic definitions of Faust entities, but your code is too tough for me to read.

**Comment by chobeat** [comment]
Ok, currently this is the code I'm using.

```
for transformation in get_transformations(config):


    async def _func(messages):
        async for message in messages:
            result = transformation.function(message)
            await output_results(result)
            yield result

    _func.__name__=transformation.name
    app.agent(app.topic(transformation.input_topic,
                        value_serializer="raw"), name=transformation.name)(_func)
```. The name parameter is specified but it doesn't seem to change anything. Is the example clear enough? I've simplified it a bit. `transformation` is a named tuple with a `name`, a `function` that does stuff and a `input_topic`. 

I've been inspecting kafka with consumers since the beginning and what I see is that the topics are all created correctly, the message I send for testing is present in the right topic but then the wrong agent run.

For example, this is the layout:

```
┌Agents───────────┬────────────────────────────┬───────┐
│ name            │ topic                      │ help  │
├─────────────────┼────────────────────────────┼───────┤
│ @delete_file    │ file_deletion_requested    │ <N/A> │
│ @delete_project │ project_deletion_requested │ <N/A> │
│ @store_file     │ file_uploaded              │ <N/A> │
└─────────────────┴────────────────────────────┴───────┘
```
I send a message to the topic `file_uploaded` through a producer and the agent `delete_project` receive a message (with an unexpected schema and it fails). So again, what is on kafka looks perfectly consistent to me: there's a message on `file_uploaded` and ntohing on `project_deletion_requested`. I'm not sure I'm understanding what you're asking me to check.

**Comment by chobeat** [comment]
I still haven't solved my problem despite all the suggestions.

I've made a reproducible snippet to further the discussion:

https://gist.github.com/chobeat/50e2a91dba6e90f4debd515a2cfbfdfc

In the comments you find the commands and the expected log. Version 1.5.2

**Comment by chobeat** [comment]
Hello @okeyokoro, I remember we resolved this on slack. It wasn't a Faust issue per se but it was due to how the closure was created. I don't remember the exact problem but try to move the definition of the agent somewhere else, in its own function. It matters for how Faust handles something.

**Comment by okeyokoro** [comment]
so I finally got this to work

the link in my previous comment helped understand the problem, but it won't hand you the answer to the problem. 

here's the answer:

you need to separate the following into functions (like stages in a pipeline):
- creation of a single agent
- configuration of multiple agents
- attach a single configured agent to the `Faust` app **iteratively**

here's some code:

```python
def create_agent(start_topic: str, next_topic: faust.topics.Topic):
    """Creating a single agent (with the help of closures)
 
         `start_topic`:  str
             Just a string that you can use in other functions
             to figure out how messages in that topic can be
             transformed

         `next_topic`:  faust.topics.Topic
             A faust `app.topic` instance
    """

    async def agent(stream):
        """ Send messages from one topic to another """

        async for message in stream:
            if message_should_be_transformed(start_topic):
                message = transform_message(start_topic, message)
            await next_topic.send(value=message)

    log.info(f"NEW Agent Created: ## Agent - {consumer} ##")

    return agent

def agents():
    """ Configuration of multiple agents """

    agents = []
    for topic in topics:
        agent = create_agent(topic.start, topic.next)
        agents.append((agent, topic))
    return agents

def attach_agent(agent, topic: namedtuple):
    app.agent(channel=topic.faust, name=f"{topic.start}-agent")(agent)

for agent, topic in agents():
    attach_agent(agent, topic)
```

**Comment by amorriso** [comment]
Had exactly the same issue. The above code demonstrates a working solution. The name parameter within attach_agent is required.

**Comment by amorriso** [comment]
The above demonstrates how to define agents programmatically, what is the best way of passing to a Faust worker a list of topics to watch? 
(I'm trying to watch a dynamic set of topics and wondering the best way to start a worker with a predefined set of topics)

**Comment by pembeci** [comment]
Note that if above code will run after app is already started, you need to start your new agents manually. Just attaching them to the app is not enough. This took me a while to solve, so let me put it here for future reference.

```
new_agent = app.agent(channel=..., name=...)(agent_coro)
new_agent.start()
```
