### ISSUE TITLE
Send method error

### ISSUE THREAD

**Issue by Telsho** [robinhood/faust#305]
Hello everyone,

I've been trying to process a stream on kafka, that would send particular messages to another topic. 
I've been following the example provided at : http://fauststream.com/en/latest/userguide/streams.html#through-forward-through-another-topic.

Consequently my code is the following:

````
app = faust.App(
        'hello-world',
        broker='kafka://localhost:XXXX',
        value_serializer ='raw',
)

source_topic = app.topic('test')
destination_topic=app.topic('bounce')

@app.agent(source_topic)
async def process(stream):
        async for value in stream:
                await destination_topic.send(value)
````

After starting my brokers, and all Kafka's stuff. I'm processing messages into the topic "test", and they should be send to "bounce".
Unfortunately, none of this happens and I get the get the following error  :

`[2019-03-12 20:03:16,441: ERROR]: [^-Agent*: stream2.process]: Crashed reason=TypeError('send() takes 1 positional argument but 2 were given',) 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mode/services.py", line 744, in _execute_task
    await task
  File "/usr/lib/python3.6/site-packages/faust/agents/agent.py", line 553, in _execute_task
    await coro
  File "/home/user/stream2.py", line 15, in process
    await destination_topic.send(value)
TypeError: send() takes 1 positional argument but 2 were given`

If you have any clue I would be graceful.
Thank you

# Versions

* Python 3.6
* Faust 1.4.8
* CentOS Linux7

**Comment by nemosupremo** [comment]
The [`send` method](https://faust.readthedocs.io/en/latest/reference/faust.topics.html#faust.topics.Topic.send) method only takes keyword arguments.

Try:
```python
await destination_topic.send(value=value)
```

**Comment by Telsho** [comment]
Oh ! It was this, thank you !
