### ISSUE TITLE
Application Signals are not fired

### ISSUE THREAD

**Issue by nemosupremo** [robinhood/faust#306]
I'm trying to use applications signals to do some synchronous application setup (ex. connecting to cassandra before I setup the async thread pool), but none of the configuration/init the application signals seem to get fired (or at least I don't see anything in the logs).

## Steps to reproduce

```python
#!/usr/bin/env python3
# pylint: disable=missing-docstring,not-async-context-manager
import os

import faust
import mode

KAFKA_BROKER = os.environ.get("KAFKA", "localhost:9092")

app = faust.App('test-pipeline',
                broker=f"kafka://{KAFKA_BROKER}",
                key_serializer='raw',
                value_serializer='raw',
                version=1,
                agent_supervisor=mode.CrashingSupervisor)
sample_topic = app.topic('test-topic',
                         key_type=bytes, value_type=bytes)


@app.on_worker_init
def on_worker_init(app, **kwargs):
    print(f'Working starting for app {app}')


@app.on_before_configured
def before_configuration(app, **kwargs):
    print(f'App {app} is being configured')


@app.on_configured.connect
def configure(app, conf, **kwargs):
    print(f'App {app} is configured')


@app.on_after_configured
def after_configuration(app, **kwargs):
    print(f'App {app} has been configured.')


@app.agent(sample_topic, supervisor_strategy=mode.CrashingSupervisor)
async def parse(beacons):
    async for ex in beacons.take(10, within=0.5):
        print(ex)

if __name__ == '__main__':
    app.main()
```

## Expected behavior

Tell us what you expected to happen.

## Actual behavior

None of the registered application signals are fired.

# Versions

* **Python version**: 3.6.3
* **Faust version**: 1.4.7 / master
* **Operating system**: OS X
* **Kafka version**: n/a
* **RocksDB version (if applicable)**: n/a

**Comment by ask** [comment]
It should be:

`@signal.connect`

so like:

```@app.on_configured.connect
def ...```

**Comment by ask** [comment]
You should also connect the @app.on_configured etc, signals before you call `app.topic`
as calling `app.topic()` will finalize configuration right now.

**Comment by nemosupremo** [comment]
I see - the configuration signals should probably mentioned they need to be called before `app.topic` too in the docs.

Does `on_worker_init` need to be called before topic as well?

**Comment by ask** [comment]
No, on_worker_init is fine, since that signal is fired much much later.

Currently the configuration is "finalized" as soon as it's needed, and this includes accessing app.conf.Topic, the configuration key that lets you change what class is used for topics.

It's not really a bad thing though, the configuration used to have explicit finalization to make
sure nobody changes configuration after it's needed.

Since then we now warn if you set a configuration key after that key has been used:

```
>>> import faust
>>> app = faust.App('foo')
>>> topic = app.topic('foo_topic')
>>> app.conf.Topic = faust.Topic
__main__:1: AlreadyConfiguredWarning: Setting new value for configuration key 'Topic' that was already used.

Reconfiguring late may mean parts of your program are still
using the old value of <class 'faust.topics.Topic'>.

Code such as:

app.conf.Topic = <class 'faust.topics.Topic'>

Should appear before calling app.topic/@app.agent/etc.
```

One side effect is that these configuration signals are much more short lived than they used to be ;)
