### ISSUE TITLE
Update docs referring to "exactly once" in future

### ISSUE THREAD

**Issue by TomGoBravo** [robinhood/faust#312]
I read at https://faust.readthedocs.io/en/latest/userguide/tables.html#basics 

> we are hoping to take advantage of Kafka 0.11’s stronger consistency guarantees and new “exactly-once”-semantics features as soon as that is supported in a Python Kafka client.

It looks like https://github.com/robinhood/faust/pull/280 has been merged. 

Please may you update the table docs and faust/TODO.rst

Congratulations on landing a big important feature!

**Comment by ask** [comment]
Thanks! I fixed the ones you mentioned in master
