### ISSUE TITLE
Can't change the partition number of changelog topic.

### ISSUE THREAD

**Issue by zhorzh** [robinhood/faust#325]
I am trying to change the partition number of changelog topic, but i always have 8 partitions

Here is my config:
```

app = App(__name__,
          version=2,
          topic_partitions=1,
          key_serializer='json',
          value_serializer='json',
          # store='rocksdb://',
          broker='kafka://kafka:29092')
worker_commands = app.topic('worker_commands',
                            value_type=Command,
                            partitions=1)
worker_events = app.topic('worker_events',
                          value_type=Event,
                          partitions=1)
accounts = app.Table('accounts',
                     default=Account,
                     partitions=1)

```
I am expecting that the number of source topics will be equal to changelog topics

## Actual behavior
I have the partition number of source topics equals to 1
BUT the number of changelog topics is always equals to 8

## Traceback
```
faust        | [2019-03-30 20:37:11,268: ERROR]: [^---Agent*: agent.reduce_command_model]: Crashed reason=PartitionsMismatch("The source topic 'worker_events' for table 'accounts'\n
has 1 partitions, but the changelog\ntopic 'agent-v2-accounts-changelog' has 8 partitions.\n\nPlease make sure the topics have the same number of partitions\nby configuring Kafka co
rrectly.\n")
faust        | Traceback (most recent call last):
faust        |   File "/usr/local/lib/python3.7/site-packages/faust/agents/agent.py", line 601, in _execute_task
faust        |     await coro
faust        |   File "/srv/app/agent.py", line 83, in reduce_command_model
faust        |     accounts[event.aggregate_id] = account
faust        |   File "/usr/local/lib/python3.7/site-packages/mode/utils/collections.py", line 505, in __setitem__
faust        |     self.on_key_set(key, value)
faust        |   File "/usr/local/lib/python3.7/site-packages/faust/tables/table.py", line 72, in on_key_set
faust        |     self._send_changelog(event, key, value)
faust        |   File "/usr/local/lib/python3.7/site-packages/faust/tables/base.py", line 228, in _send_changelog
faust        |     self._verify_source_topic_partitions(event)
faust        |   File "/usr/local/lib/python3.7/site-packages/faust/tables/base.py", line 257, in _verify_source_topic_partitions
faust        |     change_n=change_n,
faust        | faust.exceptions.PartitionsMismatch: The source topic 'worker_events' for table 'accounts'
faust        | has 1 partitions, but the changelog
faust        | topic 'agent-v2-accounts-changelog' has 8 partitions.
faust        |
faust        | Please make sure the topics have the same number of partitions
faust        | by configuring Kafka correctly.
```

# Versions

* Python version 3.7
* Faust version 1.5.2
* Operating system Ubuntu 18.04
* Kafka version 2.1.0

**Comment by mcbex** [comment]
I am also having this problem. In my case the table changelog is correctly created with 1 partition  once I explicitly pass `partitions=1` but if I attempt to add a key-index (tumbling windowed table) the key-index changelog topic is created with 8 partitions. The partition number for the key-index does not appear to be configurable. My Kafka server is set to default to 1 partition for auto-created topics. 

Example table created with: 
```
app.Table('key-index-test', partitions=1).tumbling(60, expires=180, key_index=True)
```
Logs: 
```
+Reading Starts At - Active--------------+-----------+--------+
| topic                                  | partition | offset |
+----------------------------------------+-----------+--------+
| foo-key-index-test-key_index-changelog | 7         | -1     |
| foo-key-index-test-changelog           | 0         | -1     |
| foo-key-index-test-key_index-changelog | 4         | -1     |
| foo-key-index-test-key_index-changelog | 5         | -1     |
| foo-key-index-test-key_index-changelog | 2         | -1     |
| foo-key-index-test-key_index-changelog | 3         | -1     |
| foo-key-index-test-key_index-changelog | 0         | -1     |
| foo-key-index-test-key_index-changelog | 1         | -1     |
| foo-key-index-test-key_index-changelog | 6         | -1     |
+----------------------------------------+-----------+--------+
```
Error: 
```
faust.exceptions.PartitionsMismatch: The source topic 'foo' for table 'key-index-test-key_index'
has 1 partitions, but the changelog
topic 'foo-key-index-test-key_index-changelog' has 8 partitions.
```

Before I passed `partitions=1` to the table initialization I also got a table changelog topic with 8 partitions. Expected behavior when the parameter is not set is probably for either: 
1) table and key-index changelog topics to be created using the default partition number for Kafka (in my case 1) 
2) table and key-index changelog topics to be created using the number of partitions in the source topic

```
Python 3.6.5
faust, version Faust 1.4.8
```

**Comment by chunsejin** [comment]
Try to change the 'topic name' that made multiple partitions. 
=> app.Table('key-index-test1', partitions=1).tumbling(60, expires=180, key_index=True)

In my thought, Kafka does not accept the request on the modification of the number of partitions.

**Comment by mcbex** [comment]
> Try to change the 'topic name' that made multiple partitions

Unfortunately this does not work. I changed the topic name multiple times while testing. The key_index-changelog topic is created with 8 partitions even when the table changelog topic is created correctly. The only workaround I have found is to manually create the key_index-changelog topic with the correct number of partitions before ever initializing the table.

**Comment by ask** [comment]
@mcbex Thanks!  Very good observation! I fixed it just now in master

**Comment by LeonardAukea** [comment]
I'm not sure if this is fixed. Faust 1.8.1

```
The source topic 'icl.analytics.events.service' for table 'service_by_category'
has 5 partitions, but the changelog
topic 'demo-service_by_category-changelog' has 8 partitions.

Please make sure the topics have the same number of partitions
by configuring Kafka correctly.
```
How can I explicitly set the changelog number of partitions?

**Comment by LeonardAukea** [comment]
@ask I upgraded to Faust 1.9.0 and things are now working as expected

**Comment by LeonardAukea** [comment]
Actually disregard the above. Now it worked for a short while and the worker ccrashed again ```faust.exceptions.PartitionsMismatch: The source topic 'icl.analytics.events.service' for table 'service_by_category'
has 5 partitions, but the changelog
topic 'demo-service_by_category-changelog' has 8 partitions.

Please make sure the topics have the same number of partitions
by configuring Kafka correctly.```

**Comment by robie2011** [comment]
> @ask I upgraded to Faust 1.9.0 and things are now working as expected

not for me

**Comment by hsdtsyl** [comment]
why closed, does it resolved?

i met the same error as in faust 1.9.0

**Comment by danigosa** [comment]
@hsdtsyl 
same here with Faust 1.10.1, I had to disable `KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'` for the docker compose services and in real prod settings in order to work. If I do not remember wrongly, that's already documented somehow that auto created topics do not respect partitions.

**Comment by imranshaikmuma** [comment]
facing the same issue on 1.10.3 version

**Comment by LeonardAukea** [comment]
@ask Is this issue supposed to be resolved by using this workaround by @mcbex ? 

> The only workaround I have found is to manually create the key_index-changelog topic with the correct number of partitions before ever initializing the table.

Without this I'm experiencing unreliable behaviour :/  Also, what is the reason for defaulting to 8 partitions?

**Comment by sagungargs15** [comment]
I am also facing this issue in latest version of faust. What is the resolution for this ?

**Comment by kigawas** [comment]
> I am also facing this issue in latest version of faust. What is the resolution for this ?

See this: https://github.com/robinhood/faust/issues/358#issuecomment-722891283
