### ISSUE TITLE
documentation on blessed keys is incomplete

### ISSUE THREAD

**Issue by fmux** [robinhood/faust#327]
Commit 9d92b5c6c47150653450066b95a7e1303e77a55e has introduced [documentation on blessed keys, polymorphic fields and the `allow_blessed_key` parameter](https://faust.readthedocs.io/en/latest/userguide/models.html#blessed-keys-and-polymorphic-fields). Unfortunately, the documentation in the current state (1.5.2 as well as current master) opens more question than it answers:

- The `Asset` example doesn't make it clear what the relationship between `Asset`, `ImageAsset` and `VideoAsset` is - should the latter two be derived from the former instead of `faust.Record`?
- The `allow_blessed_key` parameter is introduced in this example, but neither explicitly mentioned nor documented anywhere else. In particular, when playing around with this example, I have not been able to spot any difference in behavior when supplying this key or leaving it out.
- After introducing the `Asset` example, the documentation mentions blessed keys and proceeds to deal with the `Account` example constructed before, without ever actually going back to the topic of polymorphic fields.

Sorry for not supplying a proper pull request, unfortunately I don't really see how this feature is supposed to work myself.

**Comment by ask** [comment]
I updated the docs, let me know if they are still missing any detail!

**Comment by fmux** [comment]
Awesome, thank you!

In particular, the two paragraphs
> By default we don't use this name for anything at all, but we do if polymorphic fields are enabled.
> 
> Why is it disabled by default? There is often a mismatch between the name of the class used to produce the event, and the class we want to reconstruct it as.

clear up lots of confusion, I think.
