### ISSUE TITLE
How to define the web port in faust application?

### ISSUE THREAD

**Issue by Mahamutha** [robinhood/faust#332]
I am unable to run two different faust applications. Could you please help me out to define the web port in faust application?

>
          worker  = Worker(app, loglevel="INFO")
          worker.execute_from_commandline()

**Comment by Mahamutha** [comment]
@andresjaor , I got it. But I dont know, how to use that option, when I run the application as worker
`    
    if __name__ == '__main__':
    worker = Worker(app,  loglevel="INFO")
    worker.execute_from_commandline()`

**Comment by Mahamutha** [comment]
> you can use the worker `--web-port` or `-p` option.
> [see reference](https://faust.readthedocs.io/en/latest/userguide/cli.html#id10)

I have built an application using worker i.e.,

> app = faust.App('channel')

> class  MyModel(faust.Record):
              x: int

> channel  = app.channel(value_type=MyModel)



`
if __name__ == '__main__':
`

> 

    worker = Worker(app)
    worker.execute_from_commandline()

How can I pass the web port as a parameter to worker? Is there any option or Should I use only command line parameters?

**Comment by chobeat** [comment]
I have the same problem, especially because if I have more than one app, they try to use the same port and they crash. Now I'm forced to run with the webport disabled using `web_enabled=False`

**Comment by Mahamutha** [comment]
> I have the same problem, especially because if I have more than one app, they try to use the same port and they crash. Now I'm forced to run with the webport disabled using `web_enabled=False`

"Web_enabled=False" in the worker section

**Comment by bobh66** [comment]
You could try setting os.environ['WEB_PORT'] before you invoke the Worker - it should use that as the default value for the web port as if it were entered on the command line.

**Comment by zibuyu1995** [comment]
Setting up when initializing app
```python
faust_app = APP(
    id='web',
    loop=loop,
    web_port=7001,
)
```

**Comment by Mahamutha** [comment]
@zibuyu1995, Thank you. Setting up a web port in the app initialisation works fine.
