### ISSUE TITLE
Error when producing to a topic whe exactly_once is enabled

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [robinhood/faust#339]
## Checklist

- [x] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Hi, If I enable exactly once support, and try to publish an event to a topic I get a `TypeError: 'NoneType' object is not iterable`. I tried 3 methods that I know to publish to a topic: `sink`, `event.forward()` and `topic.send()`. I get the same error with all methods. I'm testing in a kafka cluster with 6 nodes, the source topic has 8 partitions and 3 replicas, all destination topics also have 8 partitions and 3 replicas.

With the exact sample code below, if I comment ou the `processing_guarantee='exactly_once'`, everything works as expected.

## Expected behavior

I expect the message to be produced to the topics.

## Actual behavior

TypeError: 'NoneType' object is not iterable

## Full traceback

```pytb
[^---Agent*: filter_events.process]: Crashed reason=TypeError("'NoneType' object is not iterable",) 
Traceback (most recent call last):
  File "/home/daniel/.virtualenvs/tributum-accounts/lib/python3.6/site-packages/faust/agents/agent.py", line 601, in _execute_task
    await coro
  File "/home/daniel/.virtualenvs/tributum-accounts/lib/python3.6/site-packages/faust/agents/agent.py", line 638, in _slurp
    await self._delegate_to_sinks(value)
  File "/home/daniel/.virtualenvs/tributum-accounts/lib/python3.6/site-packages/faust/agents/agent.py", line 645, in _delegate_to_sinks
    await cast(TopicT, sink).send(value=value)
  File "/home/daniel/.virtualenvs/tributum-accounts/lib/python3.6/site-packages/faust/topics.py", line 184, in send
    callback=callback,
  File "/home/daniel/.virtualenvs/tributum-accounts/lib/python3.6/site-packages/faust/channels.py", line 218, in _send_now
    key_serializer, value_serializer, callback))
  File "/home/daniel/.virtualenvs/tributum-accounts/lib/python3.6/site-packages/faust/topics.py", line 373, in publish_message
    headers=headers,
  File "/home/daniel/.virtualenvs/tributum-accounts/lib/python3.6/site-packages/faust/transport/consumer.py", line 262, in send
    p: int = self.consumer.key_partition(topic, key, partition)
  File "/home/daniel/.virtualenvs/tributum-accounts/lib/python3.6/site-packages/faust/transport/consumer.py", line 1191, in key_partition
    return self._thread.key_partition(topic, key, partition=partition)
  File "/home/daniel/.virtualenvs/tributum-accounts/lib/python3.6/site-packages/faust/transport/drivers/aiokafka.py", line 468, in key_partition
    all_partitions = list(metadata.partitions_for_topic(topic))
TypeError: 'NoneType' object is not iterable
```
## Code used

```python
import faust

VERSION = 117

app = faust.App(
    'filter_events',
    processing_guarantee='exactly_once',
    broker='kafka://localhost:19092',
    store='rocksdb://',
    version=VERSION
)

# source topic
source = app.topic('example-source-topic')

# Topics
dest1 = app.topic(f'example-dest-topic1-{str(VERSION)}')
dest2 = app.topic(f'example-dest-topic2-{str(VERSION)}')


@app.agent(source)
async def process(stream):
    async for event in stream.events():
        key = event.key.decode('utf-8')
        if 'topic1' in key:
            await event.forward(dest1)
        elif 'topic2' in key:
            await event.forward(dest2)
```

# Versions

* Python 3.6.7
* Faust 1.6.0
* Operating system Ubuntu 18.10
* Kafka version 2.2.0
* RocksDB version (if applicable) 0.7.0

**Comment by ask** [comment]
Turns out this breaks in the `forward` operation simply because the topics have not been created!

When consuming from topics we ensure that they are created, but in this case you do not consume from them.

You can create them manually in the code:

```py

@app.agent(source)
async def process(stream):
    await dest1.maybe_declare()
    await dest2.maybe_declare()
    async for event in stream.events():
        key = event.key.decode('utf-8')
        if 'topic1' in key:
            await event.forward(dest1)
        elif 'topic2' in key:
            await event.forward(dest2)
```

or you can create them using the kafka topics command line utility or similar.

I will modify the error message so it makes that more clear!

**Comment by ask** [comment]
I was wrong, turns out the issue was for a completely different reason.

The issue was that these topics were not under transactional control.

I wrote a patch, and now it works for me, but please try it out and tell me if it's working for you!

**Comment by DanielFerreiraJorge** [comment]
Thanks for the answer. It was not that, the topics are pre-created via kafka command line. In any case, I also tried `maybe_declare()` and it did not work either. I will try the patch and get back to you!

**Comment by DanielFerreiraJorge** [comment]
The patch worked!
Thanks!
