### ISSUE TITLE
Question: Deployment and secrets for AWS

### ISSUE THREAD

**Issue by ccotar** [robinhood/faust#347]
What is the common/recommended deployment strategy for Faust?

Should I be making python files for every operation and put them in docker files and then deploy those docker files to kubernetes?  Should the pipeline be one file?

If I have processes that use AWS, what is the recommended way to add these secrets to the pipeline steps?

**Comment by stevanmilic** [comment]
There is a very nice example with kubernetes: https://github.com/robinhood/faust/tree/master/examples/kubernetes

As for AWS, I suggest checking CD examples for EKS.
