### ISSUE TITLE
faust app not processing last record

### ISSUE THREAD

**Issue by bvarghese1** [robinhood/faust#352]
## Steps to reproduce
Produce data into a topic X. Started two applications 1. faust app and 2. kafka streams app. Both process the data however, the faust app does not process the last record according to the kafka-consumer-groups.sh command.

```/opt/kafka/bin/kafka-consumer-groups.sh --bootstrap-server localhost:9092 --describe --group <application_id>```

## Expected behavior

Faust app must process the last record and the kafka-consumer-groups.sh must report a lag of 0

## Actual behavior
Faust app report after running the kafka-consumer-groups.sh command:
<img width="1673" alt="Screen Shot 2019-05-15 at 1 46 21 PM" src="https://user-images.githubusercontent.com/10199670/57808280-dc91b300-7717-11e9-9c39-aeab9d8f1f37.png">

# Versions

* Python version - 3.7.3
* Faust version - 1.4.5
* Operating system - Ubuntu 18.04.2 LTS
* Kafka version - 2.1
* RocksDB version (if applicable)

**Comment by StephenSorriaux** [comment]
Hi,

The last message is actually processed. It is the way Faust currently commits its offset that differs from other project, which leads to `kafka-consumer-groups.sh` showing a lag of 1. More explanations here: https://github.com/robinhood/faust/issues/73

**Comment by bvarghese1** [comment]
Duplicat of #73
