### ISSUE TITLE
partitions argument for Table is ignored

### ISSUE THREAD

**Issue by sohaibfarooqi** [robinhood/faust#358]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

```python
import faust

app = faust.App(
  'test',
  version=1,
  broker='kafka://localhost:9092',
  store='memory://',
  topic_partitions=2,
  processing_guarantee='exactly_once',
)

class Model(faust.Record):
  a: int
  b: int

test_topic = app.topic(
  'test_topic',
  value_type=Model,
  partitions=2
)

test_table = app.Table(
  'test_table',
  default=int,
  partitions=2
)

@app.agent(test_topic)
async def process(test_stream):
  async for stream in test_stream:
    test_table[stream.a] += 1

@app.timer(5)
async def produce():
  for i in range(10):
    obj = Model(i, i+1)
    await test_topic.send(value=obj)
```

## Expected behavior

The above script should create 2 partitions for both `test_topic` and 
`test-test_table-changelog`.

## Actual behavior

Kafka shows only 1 partition being created for `test_topic`:

```shell
 ./kafka-topics.sh --describe --zookeeper localhost:2181 --topic test_topic
Topic:test_topic	PartitionCount:1	ReplicationFactor:1	
Configs:
Topic: test_topic	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
```
The number of parition for `test-test_table-changelog` is correct:

```shell
./kafka-topics.sh --describe --zookeeper localhost:2181 --topic test-test_table-changelog
Topic:test-test_table-changelog	PartitionCount:2	ReplicationFactor:1	
Configs:cleanup.policy=compact
Topic: test-test_table-changelog	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
Topic: test-test_table-changelog	Partition: 1	Leader: 0	Replicas: 0	Isr: 0

```

Faust worker log:

```
┌Highwater - Active─────────┬───────────┬───────────┐
│ topic                     │ partition │ highwater │
├───────────────────────────┼───────────┼───────────┤
│ test-test_table-changelog │ 0         │ -1        │
│ test-test_table-changelog │ 1         │ -1        │
└───────────────────────────┴───────────┴───────────┘ 
[2019-06-04 13:56:34,786: INFO]: [^---Recovery]: active offsets at start of reading:
┌Reading Starts At - Active─┬───────────┬────────┐
│ topic                     │ partition │ offset │
├───────────────────────────┼───────────┼────────┤
│ test-test_table-changelog │ 0         │ -1     │
│ test-test_table-changelog │ 1         │ -1     │
└───────────────────────────┴───────────┴────────┘ 
[2019-06-04 13:56:35,793: INFO]: [^---Recovery]: standby offsets at start of reading:
┌Reading Starts At - Standby─┐
│ topic │ partition │ offset │
└───────┴───────────┴────────┘
```
## Full traceback

```pytb
[2019-06-04 13:56:37,800: ERROR]: [^---Agent*: test.process]: Crashed reason=PartitionsMismatch("The source topic 'test_topic' for table 'test_table'\nhas 1 partitions, but the changelog\ntopic 'test-test_table-changelog' has 2 partitions.\n\nPlease make sure the topics have the same number of partitions\nby configuring Kafka correctly.\n",) 
Traceback (most recent call last):
  File "/Users/sohaibfarooqi/projects/faust_test/.env/lib/python3.6/site-packages/faust/agents/agent.py", line 601, in _execute_task
    await coro
  File "/Users/sohaibfarooqi/projects/faust_test/test.py", line 32, in process
    test_table[stream.a] += 1
  File "/Users/sohaibfarooqi/projects/faust_test/.env/lib/python3.6/site-packages/mode/utils/collections.py", line 505, in __setitem__
    self.on_key_set(key, value)
  File "/Users/sohaibfarooqi/projects/faust_test/.env/lib/python3.6/site-packages/faust/tables/table.py", line 72, in on_key_set
    self._send_changelog(event, key, value)
  File "/Users/sohaibfarooqi/projects/faust_test/.env/lib/python3.6/site-packages/faust/tables/base.py", line 228, in _send_changelog
    self._verify_source_topic_partitions(event)
  File "/Users/sohaibfarooqi/projects/faust_test/.env/lib/python3.6/site-packages/faust/tables/base.py", line 257, in _verify_source_topic_partitions
    change_n=change_n,
faust.exceptions.PartitionsMismatch: The source topic 'test_topic' for table 'test_table'
has 1 partitions, but the changelog
topic 'test-test_table-changelog' has 2 partitions.

Please make sure the topics have the same number of partitions
by configuring Kafka correctly.
```

# Versions

* Python version=3.6.5
* Faust version=1.6.0
* Operating system=OSX Mojave 10.14
* Kafka version=2.20
* RocksDB version=N/A

**Comment by StephenSorriaux** [comment]
Hi,

The problem here is with the `test_topic` configuration which has only 1 partition. As the `test_topic` is "external" to Faust, its configuration will not be changed. I provided more information in this comment: https://github.com/robinhood/faust/issues/336#issuecomment-487044050

**Comment by sohaibfarooqi** [comment]
So i need to manually manage `test_topic`? Before faust worker boot up I need to make sure that `test_topic` is already there with 2 partitions?

**Comment by StephenSorriaux** [comment]
Yes, you do.

**Comment by sohaibfarooqi** [comment]
Thanks @StephenSorriaux! I find your comment very helpful. I hope someday we will be able to do this from faust.

**Comment by fgimian** [comment]
Just to add to this, it is actually possible to create the topics with Faust.  It took two steps when I tried this idea out.

1. Disable auto-creation of Kafka topics in your Kafka server.properties

   ```auto.create.topics.enable=false```

2. In your agent (before your `async for`), run the declare method to create the topic

   ```python
   await greetings_topic.declare()
   ```

Hope this helps
Fotis

**Comment by kigawas** [comment]
You can also try `app.topic('name', ..., internal=True)` to specify it as an internal topic.

Ref:
https://faust.readthedocs.io/en/latest/reference/faust.topics.html
> Number of partitions for these topics. On declaration, topics are created using this. Note: If a message is produced before the topic is declared, and autoCreateTopics is enabled on the Kafka Server, the number of partitions used will be specified by the server configuration.

http://fauststream.com/en/latest/userguide/channels.html
> Some channels may require you to declare them on the server side before they’re used. Faust will create topics considered internal but will not create or modify “source topics” (i.e., exposed for use by other Kafka applications).
