### ISSUE TITLE
Global cache to share configuration data

### ISSUE THREAD

**Issue by apapikyan** [robinhood/faust#366]
## Checklist

- [ ] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Currently there is no global cache support in Faust

## Expected behavior

I need to store some app preferences in a shared table which always has up to date data.
I need to be able to update the table from any of the nodes and be able to get the updated values anywhere in the app.

## Actual behavior

Not supported.

## Full traceback

```pytb
Paste the full traceback (if there is any)
```

# Versions

* Python version
* Faust version
* Operating system
* Kafka version
* RocksDB version (if applicable)

**Comment by ask** [comment]
We need to implement global tables (GlobalKTable).

Should be a matter of just changing the partition assignor to make everyone a standby for global tables.

**Comment by apapikyan** [comment]
I have added GlobalTable interface identically as it's done for Tables.
So now I can do `glob_tbl = app.GlobalTable('glob_tbl', default=int, partitions=1)` and it works as table.
Now trying to go deeper into partitions assignment, checking `partition_aasignor.py` file.
Can you give some hints about implementation details, please ?
