### ISSUE TITLE
There's no way to configure LRU key_size_limit

### ISSUE THREAD

**Issue by jpzk** [robinhood/faust#372]
I'm running Faust 1.7.0, there is no way to configure the underlying LRUCache. E.g. in my case, I need to set the LRUCache key size limit to 0. The default value is fixed to 10.000 keys. Here it does not take into account, that the value could be potentially big, so it will blow up the memory (there's no storage size limit set).

https://github.com/robinhood/faust/blob/3cf078a6239b29f442f05cf318fda96264e37204/faust/stores/rocksdb.py#L152

https://github.com/robinhood/faust/blob/3cf078a6239b29f442f05cf318fda96264e37204/faust/stores/rocksdb.py#L165

## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Consume from a topic, store something in a table, where value is big.

## Expected behavior

It should not run out of memory.

## Actual behavior

It runs out of memory, since values for 10.000 keys are cached.

## Full traceback

```pytb
Paste the full traceback (if there is any)
```

# Versions

* Python version 3.7
* Faust version 1.7
* Operating system MacOS
* Kafka version 2.1
* RocksDB version (if applicable)

**Comment by ankitchiplunkar** [comment]
This is an important issue

**Comment by sidshekhar** [comment]
this is actually a *very* pertinent need for us. Our production systems are suffering from memory issues due to this. ^
