### ISSUE TITLE
Implementation question: Access stream by key?

### ISSUE THREAD

**Issue by milankaku** [robinhood/faust#387]
I do not have a bug, but rather an implementation question. I see that you can send a stream with the key attached.

Is it possible, as more streams are coming in with different keys, to then go back to that topic and retrieve the latest stream with that key and value? How would that look with a worker?

More context: I have a worker that puts streams with a key value pair on the topic, another worker is reading from that topic and performing some calculations. Later on down the line, I need another microservice that will get a key and needs to go back to the original topic and retrieve that stream. Is that possible and how would I implement that? Is there something in the docs you can point me to, because I have not seen anything for this yet.

**Comment by ask** [comment]
This sounds like a table to me: https://faust.readthedocs.io/en/latest/userguide/tables.html

You can query tables using the built-in faust web server:

`GET http://example.com:6066/table/{table_name}/{key}/`

This is much more efficient than "go back to original topic and retrieve that stream"
