### ISSUE TITLE
Dynamically add/remove app dependencies

### ISSUE THREAD

**Issue by martinmaillard** [robinhood/faust#398]
I have a weird use case where I need to dynamically start/stop services after the app has already started.

I don't think Faust provides a way stop/disconnect a service at runtime out of the box. Here's how I'm doing it:
```python
class MyService(mode.Service):
    ...

# To start a service
service = MyService()
await app.add_runtime_dependency(service)

# To stop a service
await service.stop()
app._children.remove(service)
```

Am I missing anything to properly start/stop services and connect/disconnect them from the main app?

Would it make sense for me to submit a PR to add a `stop_runtime_dependency` method to `faust.App`?

**Comment by ask** [comment]
We can add that, but that should be added to mode.Service in that case!

**Comment by martinmaillard** [comment]
Right! Sorry about that. I'll create a PR on mode then.

**Comment by martinmaillard** [comment]
A new `Service.remove_dependency` method was added in mode. I'll close this.
