### ISSUE TITLE
Handling "Timer ... woke up too late" in stream processing?

### ISSUE THREAD

**Issue by joekohlsdorf** [robinhood/faust#404]
When stream processing I have to pass batches to some external library which takes a couple of seconds to process it. In this case I get constant "Timer ... woke up too late" logging.
This can be simulated with `sleep`:

## Steps to reproduce

```
#!/usr/bin/env python
import faust
import time

app = faust.App("slow-process", broker="kafka://kafka:9092")
topic = app.topic("slow-process", value_type=int)


async def slow_process(batch):
    time.sleep(15)


@app.agent(topic)
async def read_topic(stream):
    async for batch in stream.take(5, within=15):
        await slow_process(batch)


@app.timer(5)
async def produce():
    for value in range(100000):
        await read_topic.send(value=value)


if __name__ == "__main__":
    app.main()
```

## Expected behavior

No "Timer ... woke up too late" messages.

## Actual behavior

```
[2019-08-16 15:21:34,077: INFO]: Timer _main_keepalive woke up too late, with a drift of +14.02873296800044 
[2019-08-16 15:21:34,079: INFO]: Timer Monitor.sampler woke up too late, with a drift of +14.028626856000301 
[2019-08-16 15:21:34,080: INFO]: Timer Recovery.stats woke up too late, with a drift of +10.028808629000196 
[2019-08-16 15:21:34,080: INFO]: Timer livelock woke up too late, with a drift of +8.028956610000023 
```

# Versions

* Python version: 3.7.2
* Faust version: master
* Operating system: Debian Stretch
* Kafka version: 2.2

**Comment by ShadyF** [comment]
How did you solve this?

**Comment by joekohlsdorf** [comment]
By running my code in a thread like shown in the documentation of asyncio. I still sometimes get these errors but that might be due to CPU exhaustion.
I also think that Faust could do a much better job documenting this as doing ANY kind of real work will lead to this issue.

```
#!/usr/bin/env python
import faust
import time
from concurrent.futures import ThreadPoolExecutor

thread_pool = ThreadPoolExecutor(max_workers=1)

app = faust.App("slow-process", broker="kafka://kafka:9092")
topic = app.topic("slow-process", value_type=int)


def slow_process(batch):
    print("sleep for batch {}".format(batch))
    time.sleep(15)


@app.agent(topic)
async def read_topic(stream):
    async for batch in stream.take(5, within=15):
        app.loop.run_in_executor(thread_pool, slow_process, batch)


@app.timer(5)
async def produce():
    for value in range(100):
        await read_topic.send(value=value)


if __name__ == "__main__":
    app.main()
```

**Comment by birdsarah** [comment]
I tried to crib this code and got the error `RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.` 

My app is setup before my threadpool executor (in a different module actually).

**Comment by birdsarah** [comment]
I figured it out. I was `await`ing the result of my slow process when I should have `yield`:

```
def slow_process(batch):
    print("sleep for batch {}".format(batch))
    time.sleep(15)
    return True


@app.agent(topic)
async def read_topic(stream):
    async for batch in stream.take(5, within=15):
        result = yield app.loop.run_in_executor(thread_pool, slow_process, batch)
        ...do something with result
```

**Comment by birdsarah** [comment]
ok, the problem is because my slow_process is complicated and includes logging which I am handling via kafka and and asyncio call `asyncio.ensure_future(...)` this is where the loop has been lost.

**Comment by quangvuptit** [comment]
> slow_process

What sould I do when "slow_process" is a class ?

**Comment by parasjain1** [comment]
Is there a solution for this? I'm getting drifts as high as 3.5 seconds in the timer that produces frames using opencv VideoCapture.

**Comment by raaahuuulll** [comment]
Is there any particular solution to solve this issue?
Calling my function in threads worked for some time but it is causing this issue again. How to permanently fix this?
