### ISSUE TITLE
Exception in grouping function causes silent agent failure

### ISSUE THREAD

**Issue by austinnichols101** [robinhood/faust#416]
## Summary 

The Faust worker stops processing messages after running for a while due to an agent process failing silently.

## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

```
import faust
import logging
import random
import time

logger = logging.getLogger(__name__)
app = faust.App('example_silent_fail')
channel = app.channel()
t_start = time.monotonic()

def grouping_function(msg):
    # Allow for a startup period, then a random failure
    t_elapsed = time.monotonic() - t_start
    if t_elapsed > 15 and random.randint(0, 9) == 9:
        logger.error('!!! SILENT EXCEPTION !!!')
        return msg + 'A'
    else:
        return msg

@app.agent(channel)
async def agent_process(stream):
    try:
        # Disabling the take will allow the exception to be caught but the agent will still fail silently
        async for batch in stream.group_by(grouping_function, name="grouping_function").take(3, within=5):
            logger.info(f'agent_process - {batch}')
    except Exception as e:
        logger.error(f"agent_process - !!! SILENT EXCEPTION !!! {e}")
        # Agent will still fail, even with a pass
        # pass

@app.timer(interval=1)
async def send_process():
    value = random.randint(0, 9)
    logger.info(f'send_process - sending {value}')
    await channel.send(value=value)

@app.timer(interval=3)
async def status_process():
    logger.info(
        "status_process - Rebalancing: {}, Rebalances: {}, Events: {}, Messages: {}, Sent: {}, Messages/s {}".format(
            app.rebalancing,
            app.monitor.rebalances,
            app.monitor.events_total,
            app.monitor.messages_received_total,
            app.monitor.messages_sent,
            app.monitor.messages_s,
        ))
```

## Expected behavior

- Exception should be thrown.
- A mechanism is needed to catch/handle/override agent errors and failures (i.e. `on_error` or `on_agent_failure`...)

## Actual behavior

- Agent `send_process` fails silently.  Faust application appears to be running but stops processing messages.
- Removing `.take(3, within=5)` allows the error to be caught and displayed in `agent_process`. 
- After removing `.take` the error is displayed, but the agent fails (even with an exception `pass`)

# Versions

* Python version 3.7.4
* Faust version 1.7.4 
* robinhood-aiokafka==1.0.4

**Comment by patkivikram** [comment]
diff --git a/faust/streams.py b/faust/streams.py
index 5236f732..1b8d5450 100644
--- a/faust/streams.py
+++ b/faust/streams.py
@@ -618,9 +618,12 @@ class Stream(StreamT[T_co], Service):
         return self
 
     async def _format_key(self, key: GroupByKeyArg, value: T_contra) -> str:
-        if isinstance(key, FieldDescriptorT):
-            return key.getattr(cast(ModelT, value))
-        return await maybe_async(cast(Callable, key)(value))
+        try:
+            if isinstance(key, FieldDescriptorT):
+                return key.getattr(cast(ModelT, value))
+            return await maybe_async(cast(Callable, key)(value))
+        except BaseException as exc:
+            raise Skip() from exc
 
     def derive_topic(self,
                      name: str,

**Comment by patkivikram** [comment]
`diff --git a/faust/streams.py b/faust/streams.py
index 5236f732..1b8d5450 100644
--- a/faust/streams.py
+++ b/faust/streams.py
@@ -618,9 +618,12 @@ class Stream(StreamT[T_co], Service):
         return self
 
     async def _format_key(self, key: GroupByKeyArg, value: T_contra) -> str:
-        if isinstance(key, FieldDescriptorT):
-            return key.getattr(cast(ModelT, value))
-        return await maybe_async(cast(Callable, key)(value))
+        try:
+            if isinstance(key, FieldDescriptorT):
+                return key.getattr(cast(ModelT, value))
+            return await maybe_async(cast(Callable, key)(value))
+        except BaseException as exc:
+            raise Skip() from exc
 
     def derive_topic(self,
                      name: str,
`
