### ISSUE TITLE
how to produce individual messages out of input/output stream

### ISSUE THREAD

**Issue by jorgeakanieves** [robinhood/faust#428]
Is it possible to stream a topic as input, stream a topic as output but along the script produce another messages to another topic (without use kafka client library)?

For example:

```
input = app.topic('clicks')
output = app.topic('counts')

@app.agent(input)
async def count_click(clicks):
    async for count in clicks.items():
        process = Process()
        process.whatever()
        counts += process.count(count)
        await output.send(count)

class Process():
    topic : app.topic('temporal')
   __init__(topic):
     ''
    def whatever(self):
        with newclass(
            attr1=atrrvalue,
            attr1=atrrvalue2,
            attr1=atrrvalue3,
            callback=myfunc
        )

    def count(self, count):
        if(count)>0:
            return count
        else:
            return 0

    def myfunc(self, value):
        self.topic.send(value)
```

I use the python library "Process" and I receive the message "RuntimeWarning: coroutine 'Process.myfunc' was never awaited"...

I can´t update class "newclass" because it´s a Python library...

Any help?

Thanks!

**Comment by pushiqiang** [comment]
```
def myfunc(self, value):
       asyncio.ensure_future(self.topic.send(value),  loop=self.topic.loop)
```

**Comment by jorgeakanieves** [comment]
Huge! Thanks Patrik :)

**Comment by navid-kalaei** [comment]
just a hypothesis: as `send_soon` could be[ used in the non-async functions](https://faust.readthedocs.io/en/latest/reference/faust.topics.html?highlight=send_soon#faust.topics.Topic.send_soon). do you think that would be a help too?
