### ISSUE TITLE
Cannot join slack

### ISSUE THREAD

**Issue by fr-ser** [robinhood/faust#449]
## Checklist

- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Click the slack link in the master branch: 
https://join.slack.com/t/fauststream/shared_invite/enQtNDEzMTIyMTUyNzU2LTRkM2Q2ODkwZTk5MzczNmUxOGU0NWYxNzA2YzYwNTAyZmRiOTRmMzkyMDk0ODY2MjIzOTg2NGI0ODlmNTYxNTc

## Expected behavior

Getting into the slack group or having the option to ask for joining

## Actual behavior

Message: The link is no longer active. You can only join with a @robinhood.com email address

Kind of related to https://github.com/robinhood/faust/issues/438 as there is now no way of communication besides Github issues...

**Comment by mmatthews06** [comment]
@vineetgoel, the mailing list is also apparently off-limits to outsiders. I'd suggest either removing it, or updating that link as well.

For anyone who is looking for the Faust Slack channel, this is the most recent link, from the commit above:
https://join.slack.com/t/fauststream/shared_invite/enQtNDEzMTIyMTUyNzU2LTIyMjNjY2M2YzA2OWFhMDlmMzVkODk3YTBlYThlYmZiNTUwZDJlYWZiZTdkN2Q4ZGU4NWM4YWMyNTM5MGQ5OTg

I'm only copy/pasting for the Google trail. 😄
