### ISSUE TITLE
Huge memory leak when streaming from topics with many partitions

### ISSUE THREAD

**Issue by Unknown22** [robinhood/faust#455]
## Checklist

- [x] Faust version 1.8.1
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

I did a simple app with agent reading from the topic. Everything is perfect up to 8 partitions per topic. When I tried to stream from topic with 16 partitions my RAM blows up, there are some huge memory leaks and messages are not printed. I didn't try topics with more than 8 and less than 16 partitions so don't know when the problem begins.

I tried Faust 1.7.4 and there is not a problem, so it's a new bug in 1.8

## Expected behavior

I expect messages from the topic are printed.

## Actual behavior

When assigning an agent to a topic with 16 partitions messages are not printed and RAM blows up causing huge memory leak.

# Versions

* 3.7
* 1.8.1
* Ubuntu 19.04
* 2.3.x

**Comment by austinnichols101** [comment]
I'm using 1.8.1 with topics of up to 60 partitions.  

You may want to test with the code in #454 which addresses an OOM issue.

**Comment by Unknown22** [comment]
Thank you. It solved my problem.
