### ISSUE TITLE
Faust app does not consume kafka messages after  livelock: COMMIT OFFSET NOT ADVANCING

### ISSUE THREAD

**Issue by amitkg29** [robinhood/faust#458]
FAUST version: 1.7.1
Kafka Version: SCALA -2.12, KAFKA-2.1.0
PYTHON - 3.7.3

I see the error sometimes:
[2019-10-19 18:12:34,104: WARNING]: [^--Consumer]: wait_empty: Waiting for [(0, <ConsumerMessage: TopicPartition(topic='text', partition=14) offset=60157>)] tasks
[2019-10-19 18:12:34,649: WARNING]: [^--Consumer]: Possible livelock: COMMIT OFFSET NOT ADVANCING

At this time, KAFKA LAG for the given partition does not change and the consumer stays in the KAFKA consumer group for the given partition.
The only way to commit the offsets is to restart the APP.
Is there a way to handle it programmatically in FAUST APP? Or any other suggestions?

**Comment by fr-ser** [comment]
Maybe related to https://github.com/robinhood/faust/issues/450

**Comment by DhruvaPatil98** [comment]
> Maybe related to #450

The issue in 450 seems to be stemming from a commit made after release of 1.8, and seems more like a minor bug that isn't actually doing much harm (just falsely sending that message even though the messages were committed). My PR #456 addresses that (not sure in the right way, but it seems to solve that issue). 

This must be something else.

**Comment by ask** [comment]
Sounds like processing of an event is hanging somehow!

What is the agent processing this event doing?

During rebalancing we wait for whatever is currently processing to finish.
You can also disable this using `App(..., stream_wait_empty=False)`.
In the case it is disabled it will simply reprocess that message when rebalancing is complete.

**Comment by amitkg29** [comment]
Thanks All. I agree that issue seen by me is something else and not related to #450. I am seeing this issue in faust 1.7.1.

Answering to Solem - The agent is parsing the message and publish another topic after minimal processing.
I did not understand when you say - "processing of an event is hanging somehow!"

**Comment by amitkg29** [comment]
> Sounds like processing of an event is hanging somehow!
> 
> What is the agent processing this event doing?
> 
> During rebalancing we wait for whatever is currently processing to finish.
> You can also disable this using `App(..., stream_wait_empty=False)`.
> In the case it is disabled it will simply reprocess that message when rebalancing is complete.

Any clues/suggstions on my previous message?

**Comment by amitkg29** [comment]
I have been able to work around the issue by detecting the error state using Faust Monitor and restart my App. I see that there are fixes in 1.8+ on commit offset not advancing. Hence, I am closing this issue.

**Comment by sohaibfarooqi** [comment]
I am still seeing this in 1.9.0 with `stream_wait_empty=False`!

**Comment by dhatraknilam** [comment]
> I am still seeing this in 1.9.0 with `stream_wait_empty=False`!

True. stream_wait_empty is not working. Faust app hangs with continuous logs saying 
`COMMIT OFFSET NOT ADVANCING FOR TopicPartition`
I am getting this error for repartition topic. Surprisingly the key is not changing for the table. I don't understand why it is trying to repartition.

**Comment by basedav** [comment]
Was having this issue and my agent was hanging(?) because I was `return`ing instead of `yield`ing the result after processing.
