### ISSUE TITLE
Update python-rocksdb requirement to latest

### ISSUE THREAD

**Issue by austinnichols101** [robinhood/faust#464]
ref: `faust/requirements/extras/rocksdb.txt`

The specified version `python-rocksdb>=0.6.7` is quite old, from June 25, 2017.

The latest version is `python-rocksdb>=0.7.0` from Feb 1, 2019.

**Comment by bryantbiggs** [comment]
this is not an issue because the requirement states it must be greater than or equal to 0.6.7 - so you can use versions 0.6.7 through the latest (including 0.7.0)

**Comment by austinnichols101** [comment]
Fair enough.
