### ISSUE TITLE
Consume kafka message

### ISSUE THREAD

**Issue by huangxiaohen2738** [robinhood/faust#471]
```
app = faust.App(
    'myapp',
    broker='kafka://localhost:9092',
)

class Shop(faust.Record):
    sid: str
    env: str
    domain: str
    seller_id: str

shop_topic = app.topic(
    'store-info-update-event',
    #value_type=Shop)
    value_serializer='raw')


@app.agent(shop_topic)
async def process_shop(stream):
    async for shop in stream.events():
        msg = shop.message
        print(msg.value)

```

msg.value is b'\x00\x00\x00\x029\x12133383362\x0c\xe5\xa5\xb3\xe8\xa3\x85\x12ltech\x1ad[s159384123362]\x06pre\x0c\xe5\xa5\xb3\xe8\xa3\x85\x142872266210'

But I use the confluent-kafka can consume it.  why?

**Comment by sohaibfarooqi** [comment]
You are using `value_serializer='raw'` thats why you get raw data.

**Comment by huangxiaohen2738** [comment]
> You are using `value_serializer='raw'` thats why you get raw data.

If i don't use the value_serializer, it show me:
```
faust.exceptions.ValueDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by huangxiaohen2738** [comment]
> You are using `value_serializer='raw'` thats why you get raw data.

If I use the confluent-kafka, 
```
msg = AvroConsumer().poll()
msg.value()  ---> this is the value what I want.
```

**Comment by ask** [comment]
In your confluent-kafka example you use AvroConsumer, so I assume your data is using avro serialization?

Faust uses json by default, so when you define a model it will expect it to be in json, not Avro.
There is faust-avro https://pypi.org/project/faust-avro/ and registry-client https://pypi.org/project/python-schema-registry-client/

**Comment by huangxiaohen2738** [comment]
yep.thx
