### ISSUE TITLE
Python async code highlighting issue on Readthedocs

### ISSUE THREAD

**Issue by cdeil** [robinhood/faust#486]
This is a minor docs style issue.

The Python code highlighting at https://faust.readthedocs.io/en/latest/index.html could be better.

Currently "async" (and "await") doesn't seem to be recognised as a keyword, it's in white, but it should be in blue like the "def" or "class" keywords.

---

Screenshot from readthedocs (with issue):

<img width="680" alt="Screenshot 2019-12-09 at 14 34 57" src="https://user-images.githubusercontent.com/852409/70439858-33ceea80-1a91-11ea-9e27-f503ec4946c1.png">

---

Screenshot of docs I get locally (without issue):

<img width="675" alt="Screenshot 2019-12-09 at 14 35 26" src="https://user-images.githubusercontent.com/852409/70439869-38939e80-1a91-11ea-8c08-6cab3288f734.png">

---

Your RTD config looks OK, it's using a modern Sphinx version.

Why is the last build a month old?
https://readthedocs.org/projects/faust/builds/
https://readthedocs.org/projects/faust/builds/9933977/

Maybe nothing needs to be changed in the docs build config, you just need to trigger a new RTD build?

**Comment by ask** [comment]
Thanks! Looks like this was fixed in a recent Sphinx version.

I'm not sure why the RTD build is not automatic, we have the webhook installed but somehow we have to trigger it manually.

I did so just now and the docs look better

**Comment by cdeil** [comment]
@ask - Nice. Thanks!
