### ISSUE TITLE
Sentry logging handler for Faust Apps

### ISSUE THREAD

**Issue by vineetgoel** [robinhood/faust#51]
It would be nice to be able to configure a faust app to send logging into Sentry by simply adding a Sentry dsn.

**Comment by naveenreddyin** [comment]
Hi guys, any info about this?

**Comment by panasenco** [comment]
@naveenreddyin Take a look at [faust/contrib/sentry.py]( https://github.com/robinhood/faust/blob/master/faust/contrib/sentry.py)
