### ISSUE TITLE
changelog topic updation generates error

### ISSUE THREAD

**Issue by neeraj0284** [robinhood/faust#568]
I am new to faust. I know that every update to table's content pushes an update to changelog topic. But on updating a key, I am getting the following error :- 

 [WARNING] Got error produce response on topic-partition TopicPartition(topic='hello-app-views2-changelog', partition=0), retrying. Error: <class 'kafka.errors.NotEnoughReplicasError'> 

Can anyone suggest a solution??
Thanks

**Comment by StephenSorriaux** [comment]
Hello,

Seems like the changelog topic was created with fewer replica than the `min.insync.replica` configuration value of your Kafka server.

**Comment by neeraj0284** [comment]
@StephenSorriaux thanks but can you tell me how to overwrite the default replication value i.e 1 in faust for every intermediate created topic

**Comment by StephenSorriaux** [comment]
You have the `topic_replication_factor` parameter for that (https://faust.readthedocs.io/en/latest/userguide/settings.html#topic-replication-factor)

**Comment by billaram** [comment]
@ask  Can you tell when faust 1.11 will be released?

**Comment by neeraj0284** [comment]
@StephenSorriaux but i am not able to overwrite it. Can you please tell me how to overwrite topic_replication_factor inside my code.

**Comment by StephenSorriaux** [comment]
This is a parameter for the `faust.App()` object and it will be considered only at the topic creation time. If the topic is already there, Faust will not update it, and you will need to increase the number of replica yourself using the Kafka scripts or any useful tool you might know. Or, if this is just some dev tests, simply delete the topic and restart your app.
