### ISSUE TITLE
sasl scram support

### ISSUE THREAD

**Issue by smedegaard** [robinhood/faust#601]
Both aiokafka and Confluent kafka supports scram authentication. Faust should too

**Comment by popadi** [comment]
Hey! What is the status for this? Any plans on having all the other mechanisms available like they do in faust-streaming/faust? See here https://github.com/faust-streaming/faust/blob/master/faust/types/auth.py#L23-L27.

**Comment by smeana** [comment]
How do you specify mechanism=SASLMechanism.SCRAM_SHA_512? 
Using version 1.10.4 
I can only see PLAIN and GSSAPI

```
class SASLMechanism(Enum):
    PLAIN = 'PLAIN'
    GSSAPI = 'GSSAPI'
```
 
 How can I make this work for SASL_SSL with SCRAM_SHA_512?
 ssl_context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH, cafile='../certs.pem')
```
 app = faust.App('cod_error_count_sap',
                autodiscover=True,
                broker=[
                    URL("kafka://....:9093"),
                    URL("kafka://.....:9093"),
                    URL("kafka://......:9093"),
                    URL("kafka://.....:9093"),
                    URL("kafka://.....:9093"),
                ],
                broker_credentials=faust.SASLCredentials(username='......', password='......',
                                                         ssl_context=ssl_context, mechanism=SASLMechanism.SCRAM_SHA_512),
                store='rocksdb://'
                ) 
```

**Comment by patkivikram** [comment]
This project is not maintained anymore. Please refer to the [faust-streaming](https://github.com/faust-streaming/faust) as that repo is maintained
