### ISSUE TITLE
Faust to Csound converter

### ISSUE THREAD

**Issue by fewtubefx** [robinhood/faust#667]
Is it possible to implement faust compiler with faust to csound compiler. For cabbage IDE https://cabbageaudio.com/

**Comment by bobh66** [comment]
This project is a Python Kafka framework.

You are looking for the Faust DSP proramming language - https://faust.grame.fr/

**Comment by fewtubefx** [comment]
https://revues.mshparisnord.fr/rfim/index.php?id=361
https://csound.com/docs/manual/faustaudio.html

Faust to Juce is possible, is it possible Faust to Cabage  or not ?

**Comment by bobh66** [comment]
This is not the Faust you are looking for.  Read the README file.  Try this repo for Faust DSP:   https://github.com/grame-cncm/faust

**Comment by fewtubefx** [comment]
Sorry

**Comment by marcosschroh** [comment]
@fewtubefx nice that you found the correct Faust. Can you close the issue?

**Comment by fewtubefx** [comment]
OK

**Comment by hemnast** [comment]
you guys should change your name
