### ISSUE TITLE
rocksdb fails to install on Windows

### ISSUE THREAD

**Issue by fonty422** [robinhood/faust#733]
I can't seem to install rocksdb on Windows 10, either through `pip install faust[rocksdb]` or `pip install python-rocksdb`.

Trace reveals it's an issue with compiling:

```
Building wheels for collected packages: python-rocksdb
  Building wheel for python-rocksdb (setup.py) ... error

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\debooyj\appdata\local\programs\python\python38-32\include -Ic:\users\debooyj\appdata\local\programs\python\python38-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tprocksdb\_rocksdb.cpp /Fobuild\temp.win32-3.8\Release\rocksdb\_rocksdb.obj -std=c++11 -O3 -Wall -Wextra -Wconversion -fno-strict-aliasing -fno-rtti
  cl : Command line error D8021 : invalid numeric argument '/Wextra'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
```

People do point to the issue in a few places, but there aren't any full instructions on how to overcome the issue.

I've definitely confirmed that my pip, setuptools, and wheel are up to date.

# Versions

* Python version: 3.8
* Faust version: 1.10.4
* Operating system: Windows 10
* Kafka version: 2.8
* RocksDB version : Trying to install latest

**Comment by bobh66** [comment]
Isn't this a rocksdb issue and not a faust issue?

Regardless, this project appears to have been abandoned.

You might want to check out the fork of this project - https://github.com/faust-streaming/faust

**Comment by fonty422** [comment]
Yep. You're correct. I realised not long after I posted that I should have reported the issue to rocksdb, but then forgot/failed to update here.
When you say 'this project appears to have been abandoned' what are you referring to?
