### ISSUE TITLE
SASL SCRAM authentication support

### ISSUE THREAD

**Issue by popadi** [robinhood/faust#742]
I see that this issue  https://github.com/robinhood/faust/issues/601 was closed without any conclusion. I see that [faust-streaming/faust](https://github.com/faust-streaming/faust/blob/master/faust/types/auth.py#L23-L27) has SCRAM 256 and 512 as available SASL mechanisms. Any plans on having it available for robinhood/faust too? 

Nothing more than adding those two extra options to the enum needs to be done, the underlying authentication libs will take care of everything. I can make a PR with the same changes myself if that's okay.

**Comment by bobh66** [comment]
This repo hasn't been touched in over a year, so I think it's unlikely that any changes will be merged any time soon.  faust-streaming is where all new development is happening.

**Comment by popadi** [comment]
> This repo hasn't been touched in over a year, so I think it's unlikely that any changes will be merged any time soon. faust-streaming is where all new development is happening.

So if people want to be up to date with bug fixes and features they should just switch to faust-streaming/faust? (I guess that was the main reason for the fork)

**Comment by bobh66** [comment]
@popadi - yes, the fork has a lot of fixes and improvements that are not in the base repo.

**Comment by popadi** [comment]
Thanks for the answers!
